
import { RankPost, OfficerData, AntiquityRecord } from './types';

export const INITIAL_DATA: OfficerData[] = [
  { id: '1', rank: RankPost.CEL, fixed: 20, occupied: 20, surplus: 0, surplusOfficers: [] },
  { 
    id: '2', 
    rank: RankPost.TC, 
    fixed: 60, 
    occupied: 68, 
    surplus: 8, 
    surplusOfficers: [
      { name: 'JOSE DANIEL DE LIMA NETO', role: 'Corregedor', sector: 'CG', antiquity: '2' },
      { name: 'ANAXIMANDRO TENORIO DE SA', role: 'Comandante do CPRA', sector: 'CPRA', antiquity: '6' },
      { name: 'PHELIPE ROGERIO DOS SANTOS', role: 'Diretor de Pessoal', sector: 'DP', antiquity: '28' },
      { name: 'HENRIQUE JATOBA CORREIA', role: 'Comandante do CME', sector: 'CME', antiquity: '48' },
      { name: 'SILVIO JOSE LUCIO E SILVA', role: 'Diretor de Comunicação Social', sector: 'DCS', antiquity: '45' },
      { name: 'HIRAQUE AGNNES DOS SANTOS', role: 'Comandante do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '46' },
      { name: 'THIAGO DE MORAES DUARTE OLIVEIRA', role: 'Diretor de Inteligência', sector: 'DINT', antiquity: '73' },
      { name: 'FERNANDO JOSE FERREIRA SOARES JUNIOR', role: 'Comandante do CPRSUL', sector: 'CPRSUL', antiquity: '74' }
    ] 
  },
  { 
    id: '3', 
    rank: RankPost.MAJ, 
    fixed: 140, 
    occupied: 169, 
    surplus: 29, 
    surplusOfficers: [
      { name: 'ROBERTO SANTOS PEREIRA', role: 'Chefe do Centro de Motomecanização da Diretoria de Logística', sector: 'DLOG', antiquity: '1' },
      { name: 'ADRIANO LEVY MONTEIRO SANTOS', role: 'Comandante do 14º BPM', sector: '14º BPM', antiquity: '10' },
      { name: 'ANTONIO UMBELINO DOS SANTOS FILHO', role: 'Chefe da Seção de Planejamento Educacional e Formação Continuada (DE/2)', sector: 'DEIP', antiquity: '14' },
      { name: 'RODRIGO VITAL VELOSO SOARES BOTELHO', role: 'Comandante do 8º BPM', sector: '8º BPM', antiquity: '21' },
      { name: 'ADEILSON LINS DE CARVALHO', role: 'SPO', sector: 'SPO', antiquity: '22' },
      { name: 'DANIEL SAMPAIO VALOES DA ROCHA', role: 'Comandante do Centro de Formação e Aperfeiçoamento de Praças', sector: 'CFAP', antiquity: '23' },
      { name: 'CICERO JOSE NAVARRO FERRO', role: 'Chefe da Seção de Controle de Gestão e Assentamento (DP/1)', sector: 'DP', antiquity: '29' },
      { name: 'DANIEL SOUZA DOS SANTOS', role: 'Comandante do 13º BPM', sector: '13º BPM', antiquity: '39' },
      { name: 'JOSUÉ DOS SANTOS SOUZA ELIZIÁRIO', role: 'Subdiretor de Inteligência', sector: 'DINT', antiquity: '42' },
      { name: 'JOSE AGNO DA SILVA', role: 'Chefe da Seção de Orçamento da Diretoria de Finanças', sector: 'DF', antiquity: '43' },
      { name: 'CLAUDIO VICTOR DE OLIVEIRA AMORIM', role: 'Chefe do Grupamento Aéreo', sector: 'GCG', antiquity: '46' },
      { name: 'GLAUDSON JATOBA DE OLIVEIRA', role: 'Comandante do 4º BPM', sector: '4º BPM', antiquity: '47' },
      { name: 'ARLAN SIQUEIRA DE BARROS', role: 'Chefe da SPP', sector: 'SSP', antiquity: '49' },
      { name: 'NOEMI GOMES FIRMO SOARES', role: 'Comandante do BPESC', sector: 'CPE', antiquity: '52' },
      { name: 'DAVID DELEON LOPES DA SILVA', role: 'Chefe da Seção de Apoio a Auditória da Justiça Militar', sector: 'CORREG', antiquity: '57' },
      { name: 'EDSON CARLOS BARROS CABRAL DE MELO', role: 'Chefe da Seção de Procedimentos Especiais e Correição', sector: 'CORREG', antiquity: '54' },
      { name: 'DANIEL ALMEIDA SANTOS', role: 'Chefe de Segurança de Voo do Grupamento Aéreo', sector: 'GCG', antiquity: '58' },
      { name: 'BRUNO CERQUEIRA GOMES BARROS', role: 'Chefe da Seção de Pensionistas e Dependentes', sector: 'DPS', antiquity: '59' },
      { name: 'ALEANDRO FERREIRA CAITANO', role: 'Comandante do 6º BPM', sector: '6º BPM', antiquity: '65' },
      { name: 'ANTONIO ANDRE ANDRADE DE OLIVEIRA BARBOSA', role: 'Comandante do 10º BPM', sector: '10º BPM', antiquity: '75' },
      { name: 'JÓVERSON ROCHA DOS SANTOS', role: 'Chefe da Seção de Polícia Judiciária Militar', sector: 'CORREG', antiquity: '77' },
      { name: 'DIEGO HENRIQUE BEZERRA VIEIRA', role: 'Comandante do RPMON', sector: 'RPMON', antiquity: '80' },
      { name: 'VICTOR DUARTE PINHEIRO NETO', role: 'Chefe da Coordenação de Operações', sector: 'DINT', antiquity: '81' },
      { name: 'ÍRIS DAYANA QUEIROZ DE ARAÚJO', role: 'Chefe da Patrulha Maria da Penha e Grupos Vulnerável', sector: 'PMP', antiquity: '84' },
      { name: 'THIAGO ALMEIDA FERREIRA DA SILVA', role: 'Chefe da Coordenação de Análise', sector: 'DINT', antiquity: '86' },
      { name: 'GLAUBER PATRICK DE SANTANA SANTOS', role: 'Comandante do 2º BPM', sector: '2º BPM', antiquity: '89' },
      { name: 'ALUCHAM ARAUJO FONSECA DE SENA', role: 'Subcomandante do CPRM', sector: 'CPRM', antiquity: '91' },
      { name: 'JERCIO TEIXEIRA DE FARIAS', role: 'Comandante do 11º BPM', sector: '11º BPM', antiquity: '97' },
      { name: 'HEQUIAS ALISSON SANTOS PEREIRA', role: 'Comandante do BPM-ROTAM', sector: 'CME', antiquity: '106' }
    ] 
  },
  {
    id: 'qoe-1',
    rank: RankPost.MAJ_QOE,
    fixed: 1,
    occupied: 2,
    surplus: 1,
    surplusOfficers: [
      { name: 'ALBERTO MAGNO SILVA DOS SANTOS', role: 'Chefe da Seção de Folha de Pagamentos', sector: 'DPS', antiquity: '4' }
    ]
  },
  {
    id: 'qoe-cap-maj',
    rank: RankPost.CAP_MAJ_QOE,
    fixed: 0,
    occupied: 3,
    surplus: 3,
    surplusOfficers: [
      { name: 'BENEDITO RODRIGUES FILHO', role: 'Chefe da Seção de Identificação e Registro de Produtos Controlados', sector: 'DINT', antiquity: '13' },
      { name: 'MANOEL GILVANDO DOS SANTOS SILVA', role: 'Subchefe da Assessoria do Comandante Geral', sector: 'CMD', antiquity: '15' },
      { name: 'FLAXIMAN ARRUDA DOS SANTOS', role: 'Subchefe da Seção de Inativos', sector: 'DPS', antiquity: '5' }
    ]
  },
  { 
    id: '4', 
    rank: RankPost.CAP, 
    fixed: 220, 
    occupied: 272, 
    surplus: 52, 
    surplusOfficers: [
      { name: 'ANTONIO HENRIQUE DIAS COSTA', role: 'Comandante da 10ª CPM/I', sector: '10ª CPM/I', antiquity: '2' },
      { name: 'TATIANE CAVALCANTE BARROS', role: 'P3 do Comando de Policiamento da Região Norte e Zona da Mata', sector: 'CPRNZM', antiquity: '6' },
      { name: 'EMANUELLE VITORINO DA SILVA', role: 'Subchefe do COPOM CPRM', sector: 'COPOM/CPRM', antiquity: '11' },
      { name: 'VICENTE NASCIMENTO NETO', role: 'Subcomandante do 2º BPM', sector: '2º BPM', antiquity: '19' },
      { name: 'WENDERSON VIANA GUILHERME', role: 'Subcomandante do 4º BPM', sector: '4º BPM', antiquity: '21' },
      { name: 'EMANOEL PEDOS SANTOS SILVA', role: 'Subcomandante do 3º BPM', sector: '3º BPM', antiquity: '22' },
      { name: 'REVEISON CARVALHO DOS ANJOS', role: 'P2 do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '24' },
      { name: 'DIOGO BUARQUE PEREIRA', role: 'Subcomandante do RPMon', sector: 'RPMON', antiquity: '25' },
      { name: 'MARCUS VINICIUS SILVA CAVALCANTE', role: 'Subcomandante do 9º BPM', sector: '9º BPM', antiquity: '27' },
      { name: 'GRAYSON SAMUEL DA SILVA', role: 'Subcomandante do 1º BPM', sector: '1º BPM', antiquity: '29' },
      { name: 'EVERTON ESTEVAN CABRAL DA SILVA', role: 'Subcomandante do 13º BPM', sector: '13º BPM', antiquity: '33' },
      { name: 'FRANKLIN MELO DOS SANTOS', role: 'Subcomandante do 6º BPM', sector: '6º BPM', antiquity: '34' },
      { name: 'LEONARDO CESAR JORDAO ALVES', role: 'Chefe da Seção de Licitação', sector: 'DLOG', antiquity: '35' },
      { name: 'JOSE PEDRO DOS ANJOS SILVA', role: 'Comandante da 2ª CPM/I', sector: '2ª CPM/I', antiquity: '38' },
      { name: 'WILLIAMES AZARIAS FLORENCIO DA SILVA', role: 'Chefe da Seção de Inteligência', sector: 'DINT', antiquity: '42' },
      { name: 'THIAGO HENRIQUE BARROS LESSA', role: 'Subchefe da Seção de Pensionistas (DPS)', sector: 'DPS', antiquity: '44' },
      { name: 'LAURICIO GUSTAVO SANTOS DA SILVA', role: 'P1 c/c P4 do CPM', sector: 'CPRM', antiquity: '45' },
      { name: 'CAMILA MARIA GAMA SÁ', role: 'Chefe da Seção de Planejamento de Inteligência', sector: 'DINT', antiquity: '47' },
      { name: 'SAMUEL DE JESUS TELES', role: 'Subcomandante do 10º BPM', sector: '10º BPM', antiquity: '48' },
      { name: 'BRUNO CAVALCANTE PEREIRA', role: 'Chefe da Seção de Relações Institucionais', sector: 'DCS', antiquity: '49' },
      { name: 'RODOLPHO HAMUL DE MELO MARINHO', role: 'Comandante da 3ª CPM/I', sector: '3ª CPM/I', antiquity: '52' },
      { name: 'FRANCISCO LUTIANE DE BRITTO', role: 'Comandante da 5ª CPM/I', sector: '5ª CPM/I', antiquity: '54' },
      { name: 'LARISSE LESSA DE BRITO BARBOSA', role: 'Chefe da Assessoria de Relações Institucionais', sector: 'GCG', antiquity: '58' },
      { name: 'MICHEL LINS PIMENTEL', role: 'Subcomandante do BPTran', sector: 'BPTRAN', antiquity: '66' },
      { name: 'WASHINGTON LUIZ MAGALHÃES DE MELO FILHO', role: 'Chefe da Seção de Operações (DINT)', sector: 'DINT', antiquity: '67' },
      { name: 'DANIEL PITA AMARAL', role: 'Comandante da RAIO', sector: 'RAIO', antiquity: '68' },
      { name: 'VICTOR LUIZ LOPES DA SILVA', role: 'Chefe da Seção de Inteligência (Setor 2/3)', sector: 'DINT', antiquity: '69' },
      { name: 'HUGO GABRIELL DE ALMEIDA', role: 'Chefe da Divisão de Meios da APM', sector: 'APM', antiquity: '70' },
      { name: 'DYBS SANTIAGO DE MELO BARBOSA', role: 'Chefe da Subseção de Captação de Projetos (PM4)', sector: 'PM4', antiquity: '76' },
      { name: 'MARIANA CESAR GOIS CAETANO TOLEDO', role: 'Subchefe da Ajudância Geral', sector: 'AJD GERAL', antiquity: '80' },
      { name: 'CRISLANE MARIA APARECIDA DOS SANTOS CANUTO', role: 'Chefe da Subseção de Controle de mandados', sector: 'CORREG', antiquity: '81' },
      { name: 'ISMAEL DA GUIA SILVA', role: 'P3 do CPM', sector: 'CPRM', antiquity: '83' },
      { name: 'LUIZ FELIPE DE OLIVEIRA ROCHA UGA CAMARA', role: 'Comandante da 1ª CPM/I', sector: '1ª CPM/I', antiquity: '86' },
      { name: 'KELMANY MARCIO DE ASSIS SILVA', role: 'Subcomandante do 12º BPM', sector: '12º BPM', antiquity: '91' },
      { name: 'MARIO DE FREITAS GONÇALVES CARNEIRO FILHO', role: 'Subcomandante do 14º BPM', sector: '14º BPM', antiquity: '92' },
      { name: 'SEBASTIAO GRANGEIRO BISNETO', role: 'Subcomandante do BPM-ROTAM', sector: 'ROTAM', antiquity: '93' },
      { name: 'ANDRE LUIS SOUZA DE FIGUEIROA', role: 'Subchefe de Gabinete do CMD Geral', sector: 'GCG', antiquity: '94' },
      { name: 'EDUARDO HENRIQUE SALUSTIANO SANTOS', role: 'Comandante da 6ª CPM/I', sector: '6ª CPM/I', antiquity: '95' },
      { name: 'LUIZ GUSTAVO DA SILVA BEZERRA', role: 'Chefe da Secretaria do GCG', sector: 'GCG', antiquity: '98' },
      { name: 'IGOR SARMENTO FIRMINO', role: 'Subchefe da Assessoria do Subcomandante Geral', sector: 'GSCG', antiquity: '99' },
      { name: 'RAQUEL MORAIS DA SILVA VIEGAS', role: 'Chefe do Corpo de Alunos da APM', sector: 'APM', antiquity: '100' },
      { name: 'FILLIPE ALMEIDA DE ARAUJO', role: 'Comandante da Cia de Choque', sector: 'CHOQUE', antiquity: '103' },
      { name: 'JACKELINE LEANDRO DA SILVA', role: 'Chefe da Subseção de procedimentos judiciais', sector: 'CORREG', antiquity: '105' },
      { name: 'JEFFERSON CARUZO FERREIRA', role: 'Subcomandante do 8º BPM', sector: '8º BPM', antiquity: '106' },
      { name: 'OSCAR DE FREITAS BEZERRA JUNIOR', role: 'P2 do CPRNZM', sector: 'CPRNZM', antiquity: '107' },
      { name: 'BRUNA RAFAELLE DE ASSIS SANTOS', role: 'Chefe da Subseção de Legislação (PM1)', sector: 'PM1/GCG', antiquity: '109' },
      { name: 'JOSE RENIVALDO DOS SANTOS JÚNIOR', role: 'P2 do CPRSUL', sector: 'CPRSUL', antiquity: '118' },
      { name: 'LYGIA MARIA DA SILVA MÁXIMO', role: 'P3 do CPE', sector: 'CPE', antiquity: '120' },
      { name: 'VICTOR HUGO TORRES BARROS', role: 'P1 c/c P4 do CME', sector: 'CME', antiquity: '127' },
      { name: 'PAULO CEZAR SOARES DA SILVA JUNIOR', role: 'Subcomandante do 7º BPM', sector: '7º BPM', antiquity: '121' },
      { name: 'WELLINGTON DOS ANJOS SILVA JUNIOR', role: 'Subcomandante do 5º BPM', sector: '5º BPM', antiquity: '136' },
      { name: 'FABIO CALHEIROS PEREIRA', role: 'Chefe da Seção de Planejamento (GCG)', sector: 'GCG', antiquity: '141' }
    ] 
  },
  { id: '5', rank: RankPost.TEN1, fixed: 300, occupied: 300, surplus: 0, surplusOfficers: [] },
  { id: '6', rank: RankPost.TEN2, fixed: 150, occupied: 150, surplus: 0, surplusOfficers: [] },
];

export const TC_QOEM_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '2', name: 'JOSE DANIEL DE LIMA NETO', omp: 'CORREG' },
  { antiquity: '4', name: 'PAULO EUGÊNIO DA SILVA FREITAS', omp: '2ª SEÇÃO' },
  { antiquity: '5', name: 'JORGE FRANCELINO TENORIO', omp: 'DPP' },
  { antiquity: '6', name: 'ANAXIMANDRO TENÓRIO DE SÁ', omp: 'CPRA' },
  { antiquity: '7', name: 'THAYRONILSON EMERY DOS SANTOS', omp: 'GCG' },
  { antiquity: '8', name: 'CLAUDIO JOSE DA SILVA', omp: 'CORREG' },
  { antiquity: '9', name: 'ROBERTO SANTOS JÚNIOR', omp: 'ADIDO A DP AGREGAÇÃO' },
  { antiquity: '10', name: 'SILVIO JOSÉ LÚCIO E SILVA', omp: '3ª SEÇÃO' },
  { antiquity: '11', name: 'MARIO CESAR NUNES PALMEIRA', omp: 'CPRNZM' },
  { antiquity: '14', name: 'JOSE BARBOSA SILVA JUNIOR', omp: 'CPE/CORREG' },
  { antiquity: '15', name: 'HEATHCLIFF DAMASCENO GAMA', omp: 'DCS' },
  { antiquity: '17', name: 'SANDRO RICARDO DOS SANTOS', omp: 'GCG' },
  { antiquity: '18', name: 'SIDRAITON SOARES SANTOS', omp: '5ª SEÇÃO DO EMG' },
  { antiquity: '19', name: 'JOSÉ PAULO COSTA VIEIRA', omp: 'CORREG' },
  { antiquity: '20', name: 'LUIZ SANTOS DA SILVA', omp: '1º BPM' },
  { antiquity: '21', name: 'SERGIO HENRIQUE LIMA DOS SANTOS', omp: 'EMG' },
  { antiquity: '22', name: 'MARIA ADRIANA DE SOUZA', omp: 'CPRSUL' },
  { antiquity: '23', name: 'CICERO SERCUNDINO DA SILVA', omp: '1ª SEÇÃO' },
  { antiquity: '24', name: 'LUCIANO FELIZARDO DOS SANTOS', omp: 'CPM/I' },
  { antiquity: '25', name: 'HELSON DE AZEVEDO SOUZA NETO', omp: 'APM' },
  { antiquity: '26', name: 'OSIAS ALEXANDRE FERREIRA', omp: 'DF' },
  { antiquity: '27', name: 'PHELIPE ROGÉRIO DOS SANTOS', omp: 'DP' },
  { antiquity: '28', name: 'GLAUCO PAES TORRES', omp: 'DP' },
  { antiquity: '29', name: 'ANIVAN SANTOS DE SOUZA', omp: 'CPE/CORREG' },
  { antiquity: '30', name: 'GLEMERSON JATOBÁ DE OLIVEIRA', omp: 'CPRM' },
  { antiquity: '31', name: 'MOISÉS DO NASCIMENTO ACÁCIO', omp: 'DEIP/CORREG' },
  { antiquity: '32', name: 'SIDNEY INÁCIO CUNHA', omp: 'CPM/C' },
  { antiquity: '34', name: 'DIOGO VITAL DE OLIVEIRA', omp: 'CPRA' },
  { antiquity: '36', name: 'ROBERTO FELICIANO COSTA DA SILVA', omp: 'DLOG' },
  { antiquity: '37', name: 'MARCELO FERREIRA LIMA VALOES', omp: 'GSCG' },
  { antiquity: '38', name: 'HERBERT ALEKSANDER CARVALHO DE SANTANA', omp: '7º BPM' },
  { antiquity: '39', name: 'WINSTON DE SANTANA SILVA', omp: 'CPRSUL' },
  { antiquity: '41', name: 'EMERSON CAMARA DE CASTRO', omp: 'DF' },
  { antiquity: '44', name: 'JORGE RODRIGUES DE MORAIS JUNIOR', omp: 'DPS' },
  { antiquity: '45', name: 'HENRIQUE JATOBÁ CORREIA', omp: 'CME' },
  { antiquity: '47', name: 'ADEMAR SIQUEIRA DA SILVA NETO', omp: 'CPRS' },
  { antiquity: '48', name: 'DIEGO PEREIRA DE OLIVEIRA', omp: 'GCG' },
  { antiquity: '50', name: 'JOSÉ EDUARDO SILVA COSTA', omp: 'DLOG' },
  { antiquity: '51', name: 'LUCIANA LEITE SARMENTO', omp: 'OUVIDORA GERAL' },
  { antiquity: '52', name: 'JOSE ANDRE MOREIRA DE ALMEIDA', omp: 'DS' },
  { antiquity: '55', name: 'DJANE MENEZES DOS SANTOS MILHOMES', omp: 'CORREG' },
  { antiquity: '56', name: 'HIRAQUE AGNNES DOS SANTOS', omp: 'CPRM' },
  { antiquity: '57', name: 'SILVIO CÉSAR DA SILVA NUNES', omp: 'BPA' },
  { antiquity: '58', name: 'HARLEN LOPES MENDES', omp: 'BPTRAN' },
  { antiquity: '59', name: 'EVANDRO GUIMARÃES BEZERRA', omp: 'DLOG' },
  { antiquity: '61', name: 'CLOVES DO NASCIMENTO CORREIA', omp: 'DEIP' },
  { antiquity: '62', name: 'MOACIR DOS SANTOS FILHO', omp: 'DPS' },
  { antiquity: '64', name: 'MARCELO DA FONSECA CARNAÚBA', omp: 'DPS' },
  { antiquity: '65', name: 'JEFFERSON LUIZ TAVARES DA SILVA', omp: 'CIA' },
  { antiquity: '66', name: 'ALEX MATHIAS ANDRADE', omp: 'CPRNZM' },
  { antiquity: '67', name: 'CICERO QUEIROZ DA SILVA', omp: 'DLOG' },
  { antiquity: '68', name: 'CYLL FRANCIS AMORIM DE FRANÇA', omp: 'DPP' },
  { antiquity: '69', name: 'ANTONIO JORGE MOREIRA JUNIOR', omp: 'CME' },
  { antiquity: '70', name: 'JOSILEIDE ROMEIRO MELO DE CASTRO', omp: 'CME' },
  { antiquity: '71', name: 'THALVANNES JOSE BELEM RAMOS', omp: 'BPRV' },
  { antiquity: '72', name: 'LUCIANO JOÃO DA SILVA', omp: '5º BPM' },
  { antiquity: '73', name: 'THIAGO DE MORAES DUARTE OLIVEIRA', omp: 'DINT' },
  { antiquity: '74', name: 'FERNANDO JOSÉ FERREIRA SOARES JÚNIOR', omp: 'CPRSUL' },
  { antiquity: '75', name: 'JASIEL FRANCISCO SILVA DE ANDRADE', omp: '12º BPM' },
  { antiquity: '77', name: 'GERILO ALVES DE OLIVEIRA', omp: 'AJD GERAL' },
  { antiquity: '79', name: 'DIOGO TORRES PERDIGÃO', omp: 'DPP' },
  { antiquity: '81', name: 'JEFFERSON SANTA RITA CANUTO', omp: '4ª SEÇÃO' },
  { antiquity: '82', name: 'ANDRÉ LUIS ANIBAL CALVANO', omp: 'APM' },
  { antiquity: '83', name: 'JAMES TENÓRIO DO NASCIMENTO', omp: 'DLOG' },
  { antiquity: '85', name: 'CARLOS ALBERTO MUNIZ DE ALBUQUERQUE', omp: '3º BPM' },
  { antiquity: '88', name: 'PEDRO BARBOSA DE OLIVEIRA JUNIOR', omp: '9º BPM' },
  { antiquity: '89', name: 'LIVIO BRANDAO VILLAR', omp: 'CPRS' },
  { antiquity: '90', name: 'DIEGO SARMENTO FIRMINO', omp: 'BOPE' },
  { antiquity: '91', name: 'PEDRO HENRIQUE BASILIO HONORATO', omp: 'DEFD' },
  { antiquity: '92', name: 'JOSIMAR ARAUJO FIGUEREDO DA SILVA', omp: 'CPRA' },
];

export const MAJ_QOEM_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'ROBERTO SANTOS PEREIRA', omp: 'DLOG' },
  { antiquity: '2', name: 'ANDRÉ DIAS DOS SANTOS', omp: 'CPE/CORREG' },
  { antiquity: '5', name: 'JOSÉ PETRONIO PANTALEÃO DOS SANTOS', omp: '2ª SEÇÃO' },
  { antiquity: '7', name: 'ANDERSON CABRAL TAVARES DE LIMA', omp: 'L.E.' },
  { antiquity: '10', name: 'ROBERVAL GÍRLEY SILVA', omp: 'CPRA' },
  { antiquity: '11', name: 'ADRIANO LEVY MONTEIRO SANTOS', omp: '14º BPM' },
  { antiquity: '12', name: 'JAMES MARINHO VITAL', omp: 'CPM/I' },
  { antiquity: '15', name: 'ANTÔNIO UMBELINO DOS SANTOS FILHO', omp: 'DEIP' },
  { antiquity: '16', name: 'MARCOS AURÉLIO RIBEIRO PEREIRA', omp: '9ª CPM/I' },
  { antiquity: '17', name: 'MARCIO JEAN GOMES DA SILVA', omp: 'CPRSUL' },
  { antiquity: '18', name: 'MÁRCIO ALESSANDRO RIBEIRO PEREIRA', omp: '3ª SEÇÃO' },
  { antiquity: '20', name: 'JACKSON PEDRO DOS SANTOS LINO', omp: '7ª CPM/I' },
  { antiquity: '21', name: 'FRANCIS DA MOTA SANTOS', omp: 'CPRS' },
  { antiquity: '22', name: 'RODRIGO VITAL VELOSO SOARES BOTELHO', omp: '8º BPM' },
  { antiquity: '23', name: 'ADEILSON LINS DE CARVALHO', omp: 'SPO' },
  { antiquity: '24', name: 'DANIEL SAMPAIO VALOES DA ROCHA', omp: 'CFAP' },
  { antiquity: '25', name: 'CARLOS ALBERTO DA SILVA', omp: '1ª SEÇÃO' },
  { antiquity: '28', name: 'EURICO CORREIA LEAL', omp: 'OUVIDORIA' },
  { antiquity: '29', name: 'VANDERLEY PEREIRA DE OLIVEIRA', omp: 'CPRS' },
  { antiquity: '30', name: 'CÍCERO JOSÉ NAVARRO FERRO', omp: 'DP' },
  { antiquity: '33', name: 'POLLYANNA DE ALMEIDA BARROS', omp: '4ª SEÇÃO' },
  { antiquity: '34', name: 'DANILVA CLAUDIA ALVINO DA SILVA', omp: 'CPRNZM' },
  { antiquity: '35', name: 'ANDERSON RICARDO JANUÁRIO DA SILVA', omp: 'CPMC' },
  { antiquity: '36', name: 'MARCELO BARBOSA DE MACEDO', omp: 'CPRS' },
  { antiquity: '39', name: 'MIZAEL LEITE PESSOA JUNIOR', omp: 'CIA/FAZ' },
  { antiquity: '40', name: 'DANIEL SOUZA DOS SANTOS', omp: '13º BPM' },
  { antiquity: '41', name: 'MIGUEL VIEIRA DOS SANTOS NETO', omp: 'COPES' },
  { antiquity: '42', name: 'FERNANDO MÁRCIO BARBOSA FERREIRA', omp: 'PM3' },
  { antiquity: '43', name: 'JOSUÉ DOS SANTOS SOUZA ELIZIÁRIO', omp: 'DINT' },
  { antiquity: '44', name: 'JOSÉ AGNO DA SILVA', omp: 'DF' },
  { antiquity: '45', name: 'FÁBIO OLIVEIRA CHAVES', omp: 'BPA' },
  { antiquity: '47', name: 'CLAUDIO VICTOR DE OLIVEIRA AMORIM', omp: 'GCG' },
  { antiquity: '48', name: 'GLAUDSON JATOBÁ DE OLIVEIRA', omp: '4º BPM' },
  { antiquity: '50', name: 'ARLAN SIQUEIRA DE BARROS', omp: 'SPP' },
  { antiquity: '52', name: 'LAURA BEATRIZ ARGOLO VIEIRA', omp: 'DPP' },
  { antiquity: '53', name: 'NOÊMI GOMES FIRMO SOARES', omp: 'BPESC' },
  { antiquity: '55', name: 'EDSON CARLOS BARROS CABRAL DE MELLO', omp: 'CORREG' },
  { antiquity: '56', name: 'CLETIANO ANTONIO NAVARRO FERRO', omp: '4ª CPM/I' },
  { antiquity: '58', name: 'DAVID DELEON LOPES DA SILVA', omp: 'CORREG' },
  { antiquity: '59', name: 'DANIEL ALMEIDA SANTOS', omp: 'GCG' },
  { antiquity: '60', name: 'BRUNO CERQUEIRA GOMES BARROS', omp: 'DPS' },
  { antiquity: '61', name: 'SAMUEL SIDNEY OLIVEIRA SILVA', omp: 'CPRA' },
  { antiquity: '62', name: 'GEISON FRANÇA DA SILVA', omp: 'CFAP' },
  { antiquity: '63', name: 'ALISSON CESAR DA SILVA GAMA', omp: 'CORREG' },
  { antiquity: '65', name: 'CARLOS EDUARDO CAVALCANTE SANTOS', omp: 'CPRSUL' },
  { antiquity: '66', name: 'ALEANDRO FERREIRA CAITANO', omp: '6º BPM' },
  { antiquity: '69', name: 'CHRISDANGELO DIAS VERÇOSA', omp: 'CME/CORREG' },
  { antiquity: '72', name: 'KÁTIA CILENE DE HOLANDA CAVALCANTE VILELA', omp: 'DPP' },
  { antiquity: '73', name: 'ALEXANDRE MARTINS BISPO', omp: 'BPRV' },
  { antiquity: '74', name: 'LEIDIANE SANTOS DA SILVA', omp: 'SSP' },
  { antiquity: '75', name: 'RODRIGO MEDEIROS FERREIRA', omp: 'CPMC' },
  { antiquity: '76', name: 'ANTONIO ANDRE ANDRADE DE OLIVEIRA BARBOSA', omp: '10º BPM' },
  { antiquity: '77', name: 'SIDCLEY FREITAS CONSTANTINO', omp: '5ª SEÇÃO' },
  { antiquity: '78', name: 'JÓVERSON ROCHA DOS SANTOS', omp: 'CORREG' },
  { antiquity: '79', name: 'JOSE CEZAR PASSOS CALDAS', omp: '5ª SEÇÃO' },
  { antiquity: '81', name: 'DIEGO HENRIQUE BEZERRA VIEIRA', omp: 'RPMON' },
  { antiquity: '82', name: 'VICTOR DUARTE PINHEIRO NETO', omp: 'DINT' },
  { antiquity: '83', name: 'FABIO SILVA CALHEIROS DA ROSA', omp: '5ª SEÇÃO' },
  { antiquity: '84', name: 'MÁRIO JORGE FERREIRA DA SILVA JÚNIOR', omp: 'DPS' },
  { antiquity: '85', name: 'ÍRIS DAYANA QUEIROZ DE ARAÚJO', omp: 'DPP' },
  { antiquity: '87', name: 'THIAGO ALMEIDA FERREIRA DA SILVA', omp: 'DINT' },
  { antiquity: '88', name: 'DÁLILA MARINHO SIMÕES GALDINO DA SILVA', omp: 'DDP/PMP' },
  { antiquity: '89', name: 'THIAGO CARDOSO SOUZA', omp: 'CPE/DLOG' },
  { antiquity: '90', name: 'GLAUBER PATRICK DE SANTANA SANTOS', omp: '2º BPM' },
  { antiquity: '91', name: 'JOSÉ ANDERSON BOMFIM BARROS', omp: 'OUVIDORIA' },
  { antiquity: '92', name: 'ALUCHAM ARAUJO FONSECA DE SENA', omp: 'CPRM' },
  { antiquity: '93', name: 'HELOISA LIMA BARROS', omp: 'DINT' },
  { antiquity: '94', name: 'BRUNO EUCLIDES DOS SANTOS OLIVEIRA', omp: 'CPMI' },
  { antiquity: '97', name: 'REINALDO DE LIMA BARBOSA JUNIOR', omp: 'CFAP' },
  { antiquity: '98', name: 'JÉRCIO TEIXEIRA DE FARIAS', omp: '11º BPM' },
  { antiquity: '99', name: 'JEAN MIGUEL DA SILVA', omp: '11º BPM' },
  { antiquity: '100', name: 'DAVID DURVAL PEREIRA DA SILVA', omp: 'CPRA' },
  { antiquity: '101', name: 'HEYTOR ANÍZIO PEREIRA DA SILVA', omp: 'CME' },
  { antiquity: '102', name: 'ANDERSON LUIZ CALHEIROS OLIVEIRA', omp: '12º BPM' },
  { antiquity: '103', name: 'SAMUEL CRUZ DA COSTA', omp: 'BPESC' },
  { antiquity: '104', name: 'ANTONIO FURTUNATO DA SILVA', omp: 'DF' },
  { antiquity: '106', name: 'LUIZ GONZAGA DE MELO FILHO', omp: '8ª CPMI' },
  { antiquity: '107', name: 'HELQUIAS ALISSON SANTOS PEREIRA', omp: 'ROTAM' },
  { antiquity: '109', name: 'CARLA ANDRADE DE AZEVEDO', omp: 'SSP' },
  { antiquity: '110', name: 'JOHNATAN BARBOSA DE FARIAS', omp: 'DEFD' },
  { antiquity: '112', name: 'THAYLLA KAROLINE POVOAS TEIXEIRA', omp: 'SSP' },
  { antiquity: '115', name: 'JOSÉ WILLYAN FIRMINO NUNES', omp: 'CFAP/SUBCMD' },
  { antiquity: '116', name: 'GUSTAVO LUÍS DE OLIVEIRA SOUZA', omp: 'CFAP' },
  { antiquity: '117', name: 'CHARLAN WILLIAM OLIVEIRA SILVA', omp: 'DCS/DLOG' },
  { antiquity: '120', name: 'JOACY GALDINO DA SILVA JÚNIOR', omp: 'BOPE' },
];

export const MAJ_QOE_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'JOSE LEDESVAN PEREIRA DOS SANTOS', omp: 'L.E.' },
  { antiquity: '2', name: 'ANTONIO JACINTO DE LIMA', omp: 'DF' },
  { antiquity: '3', name: 'LUIZ CARLOS DE MELO GOMES', omp: 'DLOG' },
  { antiquity: '4', name: 'JOSÉ EGLIVAN MOURA SANTOS', omp: 'DLOG' },
  { antiquity: '5', name: 'ALBERTO MAGNO SILVA DOS SANTOS', omp: 'DPS' },
  { antiquity: '6', name: 'FLAVIO AZEVEDO DE OMENA', omp: 'DP' },
  { antiquity: '7', name: 'ERIVALDO SANTOS SAMPAIO', omp: 'DPS' },
  { antiquity: '10', name: 'CARLOS ALBERTO OLIVEIRA CARVALHO', omp: 'DS' },
  { antiquity: '11', name: 'SERGIO ANTONIO LIMA', omp: 'DF' },
];

export const CAP_QOEM_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'JOÃO PAULO CORREIA CAVALCANTE', omp: 'BPRV' },
  { antiquity: '2', name: 'ANTONIO HENRIQUE DIAS COSTA', omp: '10ª CPM/I' },
  { antiquity: '5', name: 'MÁRCIO JOSÉ ARAÚJO DE LIMA', omp: 'AMTJ' },
  { antiquity: '6', name: 'TATIANE CAVALCANTE BARROS', omp: 'CPRNZM' },
  { antiquity: '7', name: 'ELISABETH MAGNA DA SILVA SANTOS', omp: 'CFAP' },
  { antiquity: '8', name: 'DJALMA PEREIRA SANCHES FILHO', omp: 'ADIDO DP/DETRAN' },
  { antiquity: '9', name: 'HENRIQUE DURVAL PEIXOTO ALCÂNTARA', omp: 'DPS' },
  { antiquity: '10', name: 'ALAN ROBSON DO RÊGO GOMES', omp: 'BPRV' },
  { antiquity: '11', name: 'EMANUELLE VITORINO DA SILVA', omp: 'CPRM' },
  { antiquity: '12', name: 'LOURINALDO RODRIGUES LIMA', omp: 'CPRM' },
  { antiquity: '13', name: 'DAVI DE MELO MOTA', omp: 'CPRM' },
  { antiquity: '14', name: 'CRISTIANE SILVA PINHEIRO', omp: 'GMG' },
  { antiquity: '15', name: 'TIAGO HERCULANO DA SILVA', omp: 'CPRA' },
  { antiquity: '17', name: 'JOSÉ PEREIRA VENÂNCIO JÚNIOR', omp: 'CPRM' },
  { antiquity: '19', name: 'VICENTE NASCIMENTO NETO', omp: '2º BPM' },
  { antiquity: '20', name: 'MARCELO ALEXANDRE FREIRE COLEN', omp: 'CPRM' },
  { antiquity: '21', name: 'WENDERSON VIANA GUILHERME', omp: '4º BPM' },
  { antiquity: '22', name: 'EMANOEL PEDRO SANTOS SILVA', omp: '3º BPM' },
  { antiquity: '23', name: 'LARISSA SOARES PORCIÚNCULA', omp: 'BPA' },
  { antiquity: '24', name: 'REVEISON CARVALHO DOS ANJOS', omp: 'CPRM' },
  { antiquity: '25', name: 'DIOGO BUARQUE PEREIRA', omp: 'RPMON' },
  { antiquity: '27', name: 'MARCUS VINICIUS SILVA CAVALCANTE', omp: '9º BPM' },
  { antiquity: '28', name: 'ERINALDO NOGUEIRA DE FARIAS FILHO', omp: 'BPTRAN' },
  { antiquity: '29', name: 'GRAYSON SAMUEL DA SILVA', omp: '1º BPM' },
  { antiquity: '30', name: 'ADAILDO TENÓRIO CARMO', omp: '11º BPM' },
  { antiquity: '31', name: 'ERIVALDO ALCANTARA DE ARANDAS', omp: '2º BPM' },
  { antiquity: '32', name: 'ANTONIO AUGUSTO MOREIRA CORRÊA', omp: '4ª SEÇÃO/EMG' },
  { antiquity: '33', name: 'EVERTON ESTEVAN CABRAL DA SILVA', omp: '13º BPM' },
  { antiquity: '34', name: 'FRANKLIN MELO DOS SANTOS', omp: '6º BPM' },
  { antiquity: '35', name: 'LEONARDO CÉSAR JORDÃO ALVES', omp: 'DLOG' },
  { antiquity: '36', name: 'MICHELE BARBOSA PERCIANO DE ASSIS', omp: '10º BPM' },
  { antiquity: '37', name: 'EBER CARLOS GÓES SALES LEÃO DE OLIVEIRA', omp: 'CPMI' },
  { antiquity: '38', name: 'JOSE PEDRO DOS ANJOS SILVA', omp: '2ª CPM/I' },
  { antiquity: '39', name: 'FLÁVIA RENATA SILVA DE MOURA', omp: 'DPS' },
  { antiquity: '40', name: 'DIEGO MAHATMA DE MORAES', omp: 'SSP' },
  { antiquity: '42', name: 'WILLIAMES AZARIAS FLORÊNCIO DA SILVA', omp: 'DINT' },
  { antiquity: '43', name: 'CINIRA RAMOS DE FREITAS', omp: '2ª CPM/I' },
  { antiquity: '44', name: 'THIAGO HENRIQUE BARROS LESSA', omp: '8ªCPM/I' },
  { antiquity: '45', name: 'LAURICIO GUSTAVO SANTOS DA SILVA', omp: 'CPRM' },
  { antiquity: '46', name: 'WESLEY KELMES GOMES NOVAES SILVA', omp: 'seg. ind. (adido DP)' },
  { antiquity: '47', name: 'CAMILA MARIA GAMA DE SÁ', omp: 'DINT' },
  { antiquity: '48', name: 'SAMUEL DE JESUS TELES', omp: '10º BPM' },
  { antiquity: '49', name: 'BRUNO CAVALCANTE PEREIRA', omp: 'DCS' },
  { antiquity: '50', name: 'CARMEM LÚCIA VALÉRIO DA SILVA', omp: 'GSCG/CORREG' },
  { antiquity: '52', name: 'RODOLPHO HAMUL DE MELO MARINHO', omp: '3ª CPM/I' },
  { antiquity: '53', name: 'DARLLYNSON NASCIMENTO DOS SANTOS', omp: '3ª SEÇÃO' },
  { antiquity: '54', name: 'FRANCISCO LUTIANE DE BRITTO', omp: '5ª CPM/I' },
  { antiquity: '55', name: 'GENIVALDO BENEDITO BISPO DOS SANTOS', omp: 'CPRM' },
  { antiquity: '56', name: 'SIDCLEY DA SILVA SANTOS', omp: '2ª SEÇÃO' },
  { antiquity: '58', name: 'LARISSE LESSA DE BRITO BARBOSA', omp: 'GCG' },
  { antiquity: '60', name: 'KLENISSON EDUARDO BATISTA SANTANA', omp: '2º BPM' },
  { antiquity: '61', name: 'PRISCILA CAVALCANTE RODRIGUES FIGUEREDO', omp: 'PMP' },
  { antiquity: '62', name: 'AVNER AUGUSTO DE MORAES', omp: 'GCG/CORREG' },
  { antiquity: '66', name: 'MICHEL LINS PIMENTEL', omp: 'BPTRAN' },
  { antiquity: '67', name: 'WASHINGTON LUIZ MAGALHÃES DE MELO FILHO', omp: 'DINT' },
  { antiquity: '68', name: 'DANIEL PITA AMARAL', omp: 'RAIO' },
  { antiquity: '69', name: 'VICTOR LUIZ LOPES DA SILVA', omp: 'DINT' },
  { antiquity: '70', name: 'HUGO GABRIELL DE ALMEIDA', omp: 'APM' },
  { antiquity: '', name: 'RODOLFO ESPERIDIÃO DE MELO', omp: 'ADIDO - RESERVA' },
  { antiquity: '71', name: 'EVERTON PINHEIRO DE OLIVEIRA', omp: '13º BPM' },
  { antiquity: '72', name: 'MAXWELL DA SILVA MELO', omp: '3º BPM' },
  { antiquity: '73', name: 'JACKELINE CARNAUBA DE LIMA MARTINS', omp: 'CME/GSC' },
  { antiquity: '75', name: 'TALES TOMÉ DE SOUSA SANTOS', omp: '10º BPM' },
  { antiquity: '76', name: 'DYBS SANTIAGO DE MELO BARBOSA', omp: 'DLOG' },
  { antiquity: '77', name: 'ANDRÉ SILVA DOS SANTOS', omp: 'APMPGJ' },
  { antiquity: '78', name: 'EVELYNNE GOMES PEIXOTO DE MELO', omp: '6º BPM/DS' },
  { antiquity: '80', name: 'MARIANA CÉSAR GÓIS CAETANO TOLËDO', omp: 'AJD GERAL' },
  { antiquity: '81', name: 'CRISLANE MARIA APARECIDA DOS SANTOS CANUTO', omp: 'CORREG/GSCG' },
  { antiquity: '82', name: 'FELIPE GOMES DE SOUZA', omp: 'BPA' },
  { antiquity: '83', name: 'ISMAEL DA GUIA SILVA', omp: 'CPRM' },
  { antiquity: '84', name: 'GILVANO SILVA SANTOS JUNIOR', omp: '4ª CPM/I' },
  { antiquity: '85', name: 'LUIZ PESSOA DE MELO SOUZA', omp: 'DS' },
  { antiquity: '86', name: 'LUIZ FELIPE DE OLIVEIRA ROCHA UGÁ CÂMARA', omp: '1ª CPM/I' },
  { antiquity: '88', name: 'FELIPE CASSIMIRO DE BARROS TERTULIANO', omp: 'APM' },
  { antiquity: '89', name: 'LEONARDO LÚCIO FERREIRA CABRAL', omp: '11º BPM' },
  { antiquity: '90', name: 'HUGO CEZAR PACHECO', omp: 'CORREG' },
  { antiquity: '91', name: 'KELMANY MARCIO DE ASSIS SILVA', omp: '12º BPM' },
  { antiquity: '92', name: 'MÁRIO DE FREITAS GONÇALVES CARNEIRO FILHO', omp: '14º BPM' },
  { antiquity: '93', name: 'SEBASTIAO GRANGEIRO BISNETO', omp: 'ROTAM' },
  { antiquity: '94', name: 'ANDRÉ LUÍS SOUZA DE FIGUEIRÔA', omp: 'GCG' },
  { antiquity: '95', name: 'EDUARDO HENRIQUE SALUSTIANO SANTOS', omp: '6ª CPM/I' },
  { antiquity: '96', name: 'DIEGO BRUNO BARBOSA SANTOS', omp: 'DINT' },
  { antiquity: '97', name: 'RAMON DA SILVA RIBEIRO', omp: 'COPES' },
  { antiquity: '98', name: 'LUIZ GUSTAVO DA SILVA BEZERRA', omp: 'GCG' },
  { antiquity: '99', name: 'IGOR SARMENTO FIRMINO', omp: 'GSCG' },
  { antiquity: '100', name: 'RAQUEL MORAIS DA SILVA VIÉGAS', omp: 'APM' },
  { antiquity: '101', name: 'ROBERTA CORREIA DANTAS', omp: 'CPRM' },
  { antiquity: '103', name: 'FILLIPE ALMEIDA DE ARAÚJO', omp: 'CPCHOQUE' },
  { antiquity: '105', name: 'JACKELINE LEANDRO DA SILVA', omp: 'CORREG' },
  { antiquity: '106', name: 'JEFFERSON CARUZO FERREIRA', omp: '8º BPM' },
  { antiquity: '107', name: 'OSCAR DE FREITAS BEZERRA JÚNIOR', omp: '14º BPM' },
  { antiquity: '109', name: 'BRUNA RAFAELLE DE ASSIS SANTOS', omp: 'PM1/GCG' },
  { antiquity: '110', name: 'THIAGO LUIZ TAVARES MOURA REIS', omp: 'APM' },
  { antiquity: '111', name: 'JOSE SALATIEL COSTA BEZERRA', omp: '7ª CPM/I' },
  { antiquity: '112', name: 'DURVAL LINS DOS SANTOS NETO', omp: 'CPRM' },
  { antiquity: '113', name: 'HEYTOR ANÍZIO PEREIRA DA SILVA', omp: 'CME' },
  { antiquity: '116', name: 'ALBENES CORDEIRO DE FARIAS', omp: '10º BPM' },
  { antiquity: '117', name: 'AYRTON BISPO PEREIRA', omp: 'CORREG' },
  { antiquity: '119', name: 'JOSÉ RENIVALDO DOS SANTOS JÚNIOR', omp: 'CPRSUL' },
  { antiquity: '121', name: 'LYGIA MARIA DA SILVA MÁXIMO', omp: 'CPE/GCG' },
  { antiquity: '122', name: 'PAULO CEZAR SOARES DA SILVA JUNIOR', omp: '7º BPM' },
  { antiquity: '124', name: 'JOSÉ VITOR DE ARAÚJO SANTOS', omp: 'CGCDHPC/DPP' },
  { antiquity: '125', name: 'MAX VICTOR CAVALCANTE LIBERATO', omp: '12º BPM' },
  { antiquity: '126', name: 'ADEILTON AMADO SILVA DOS SANTOS', omp: '1º BPM' },
  { antiquity: '127', name: 'VICTOR HUGO TORRES BARROS', omp: 'CPCHOQUE' },
  { antiquity: '128', name: 'KIM ORDONIO FERREIRA', omp: '6º BPM' },
  { antiquity: '129', name: 'ALYSON MARQUES PASSOS', omp: 'BPTRAN' },
  { antiquity: '130', name: 'JOSE CLOVES DA SILVA JUNIOR ', omp: '9º BPM' },
  { antiquity: '131', name: 'WESCLEY RAFAELL FERREIRA CANUTO', omp: 'DPP' },
  { antiquity: '132', name: 'ROMUALDO GARCIA JUNIOR', omp: '11º BPM' },
  { antiquity: '133', name: 'MAXSUEL SANTOS SILVA', omp: '1ª CPM/I' },
  { antiquity: '134', name: 'BÁRBARA HERCÍLIA PADILHA DE VASCONCELOS', omp: 'CORREG' },
  { antiquity: '135', name: 'JOEMYSON LEANDRO SILVA DE SOUZA', omp: '1º BPM' },
  { antiquity: '136', name: 'WELLINGTON DOS ANJOS SILVA JUNIOR', omp: '5º BPM' },
  { antiquity: '137', name: 'RODRIGO BARBOSA FERRO', omp: '10ª CPM/I' },
  { antiquity: '138', name: 'EDUARDO DE ALMEIDA BORBA', omp: '12º BPM' },
  { antiquity: '140', name: 'TIAGO TEIXEIRA CAVALCANTE', omp: 'PM5/CGCDHPC' },
  { antiquity: '141', name: 'FÁBIO CALHEIROS PEREIRA', omp: 'GCG' },
  { antiquity: '142', name: 'NEYLA CHRISTINA PROTÁSIO MAIA', omp: 'CFAP' },
  { antiquity: '143', name: 'PAULO VICTOR DE LIMA RODRIGUES', omp: '5ª CPM/I' },
  { antiquity: '144', name: 'TAÍS PEREIRA MARABA', omp: 'CFAP' },
  { antiquity: '145', name: 'RODOLFO SILVA DE LIMA', omp: 'TJ' },
  { antiquity: '146', name: 'ILANNE CORREIA DE ANDRADE', omp: 'GCG' },
  { antiquity: '147', name: 'MARYANNY CAVALCANTE SILVA', omp: 'GMG' },
  { antiquity: '148', name: 'CARLOS RUBENS SOUZA BARROS', omp: 'GMG' },
];

export const CAP_QOE_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'JOSÉ OSMAR CLEMENTE DE BRITO', omp: '13º BPM' },
  { antiquity: '2', name: 'CLAUDIO EGIDIO NASCIMENTO CORREIA', omp: '1º BPM' },
  { antiquity: '3', name: 'JOAO VESPASIANO DE ALMEIDA', omp: 'BPA/DLOG' },
  { antiquity: '4', name: 'CARLOSMAN HENRIQUE DO CARMO JÚNIOR', omp: 'DLOG' },
  { antiquity: '5', name: 'FLAXIMAN ARRUDA DOS SANTOS', omp: 'DP' },
  { antiquity: '8', name: 'WILLIAMS OLIVEIRA PEIXOTO', omp: 'L.E.' },
  { antiquity: '9', name: 'JOSE GENALDO GOMES DOS SANTOS', omp: 'CPMI/CORREG' },
  { antiquity: '10', name: 'CRISTOVÃO MONTEIRO DA SILVA', omp: 'PM2' },
  { antiquity: '13', name: 'BENEDITO RODRIGUES FILHO', omp: 'DINT' },
  { antiquity: '14', name: 'IRAILTON RODRIGUES DE OLIVEIRA', omp: 'DF' },
  { antiquity: '15', name: 'MANOEL GILVANDO DOS SANTOS SILVA', omp: 'GCG' },
  { antiquity: '17', name: 'JOSE GERSON DA SILVA', omp: '12º BPM' },
  { antiquity: '18', name: 'ANDREY DE ALBUQUERQUE BRANDAO', omp: 'DS' },
  { antiquity: '20', name: 'ROBERTO BARROS DA SILVA', omp: '7º BPM' },
  { antiquity: '21', name: 'JOSINÉIA LIMA DOS SANTOS JUSTINO', omp: 'CPMC' },
  { antiquity: '22', name: 'PAULO ANDRE VIEIRA DOS SANTOS', omp: '8º BPM' },
  { antiquity: '23', name: 'ARLINDO CELSO LESSA CAMPOS', omp: 'DP' },
  { antiquity: '24', name: 'JOSE EDSON LOPES SIMOES', omp: 'L.E.' },
  { antiquity: '26', name: 'LENMONIEUR CHARLES CAVALCANTE', omp: '7º BPM' },
  { antiquity: '27', name: 'IRACTAN FAGUNDES DA SILVA', omp: 'CFAP' },
  { antiquity: '28', name: 'JOSÉ EMANOEL NUNES DE OLIVEIRA', omp: '4º BPM' },
  { antiquity: '29', name: 'FLÁVIO PASTOR DOS SANTOS', omp: 'APM' },
  { antiquity: '30', name: 'JOSÉ MESSIAS BATISTA DOS SANTOS', omp: 'BPESC' },
  { antiquity: '31', name: 'JOSE LUIZ SILVA DE OLIVEIRA', omp: 'BPTRAN' },
  { antiquity: '33', name: 'DACIO DOS SANTOS ROCHA', omp: 'BPRV' },
  { antiquity: '34', name: 'CLAUDIO DOS SANTOS', omp: '8º BPM' },
  { antiquity: '34', name: 'SANDRO LUIZ FERREIRA', omp: '6º BPM' },
];

export const TEN_QOEM_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'WELLINGTON AURELIANO DA SILVA', omp: 'DPP' },
  { antiquity: '2', name: 'PEDRO AURELIO TEIXEIRA LIMA GOMES', omp: 'DINT' },
  { antiquity: '3', name: 'HELIOMAR DOS SANTOS VIEIRA', omp: '8º BPM' },
  { antiquity: '4', name: 'YURE MOREIRA DE ALMEIDA', omp: 'DPS' },
  { antiquity: '5', name: 'JANDERSON DA SILVA MARQUES', omp: 'CFAP/DLOG' },
  { antiquity: '6', name: 'RONALD MEDEIROS MOTA', omp: '6ª CPM/I' },
  { antiquity: '7', name: 'PHILIPPE NASCIMENTO MARINHO', omp: '1º BPM' },
  { antiquity: '8', name: 'MARILIA DE LIMA SANTOS', omp: 'GCG' },
  { antiquity: '9', name: 'PAULO BEZERRA DOS SANTOS', omp: '10º BPM' },
  { antiquity: '10', name: 'FELIPE JOSÉ AMORIM FOSATTO', omp: 'DCS' },
  { antiquity: '11', name: 'THIAGO BRANDÃO DE LEMOS INÁCIO', omp: 'RAIO' },
  { antiquity: '12', name: 'EVELINE CASTRO DE MESQUITA', omp: 'GSI do Gover' },
  { antiquity: '13', name: 'SILVIO DA SILVA', omp: 'DF' },
  { antiquity: '15', name: 'CLÁUDIO HENRIQUE SANTOS DO CARMO', omp: '3ª CPM/I' },
  { antiquity: '16', name: 'JOSÉ MURILO TENÓRIO MAGALHÃES', omp: 'COPES' },
  { antiquity: '17', name: 'MELRISON SILVA DE LIMA', omp: '1ª CPM/I' },
  { antiquity: '18', name: 'MAURICIO ARAUJO ALMEIDA', omp: '10ª CPM/I' },
  { antiquity: '19', name: 'RAQUEL SOUZA SILVA', omp: '8º BPM' },
  { antiquity: '20', name: 'JOSÉ ROBSON SOARES JÚNIOR', omp: 'ROTAM' },
  { antiquity: '21', name: 'LUPPIO RAFAEL CARDEAL TENORIO', omp: 'L.E.' },
  { antiquity: '22', name: 'LUCIANO LUCAS ARAUJO DA SILVA', omp: '7ª CPM/I' },
  { antiquity: '23', name: 'CELSO AUGUSTO CORREIA DA SILVA', omp: '4º BPM' },
  { antiquity: '24', name: 'IGO IVISSON DE OLIVEIRA PASSOS', omp: 'BPA' },
  { antiquity: '25', name: 'EVERALDO BEZERRA DA SILVA JUNIOR', omp: '8º BPM' },
  { antiquity: '26', name: 'QUEDNIS CRUZ DE MELO', omp: 'APM' },
  { antiquity: '27', name: 'GIORGENS KLERYSSON BEZERRA SILVA', omp: '8º BPM' },
  { antiquity: '28', name: 'RAFAEL E SILVA GAMA', omp: 'CPMC' },
  { antiquity: '29', name: 'EMERSON CORREIA DE ANDRADE', omp: 'BPTRAN' },
  { antiquity: '30', name: 'JORGE ALEXANDRE DA SILVA JUNIOR', omp: '10º BPM' },
  { antiquity: '31', name: 'CARLOS RAPHAEL ANDRADE DE SANTANA', omp: '9ª CPM/I' },
  { antiquity: '32', name: 'JOAQUIM DELMIRO BISPO NETO', omp: 'BPA' },
  { antiquity: '34', name: 'CLEYLTON GUEDES PESSOA', omp: '4º BPM' },
  { antiquity: '35', name: 'HELIO JAMERSON DE AMORIM ALENCAR', omp: '13º BPM' },
  { antiquity: '37', name: 'ITALO ALMEIDA BRANDAO', omp: 'RPMON' },
  { antiquity: '38', name: 'ISAIAS AUGUSTO DA SILVA JUNIOR', omp: 'RPMON' },
  { antiquity: '39', name: 'FRANKLIM ROOSIVELT DOS SANTOS', omp: 'GSCG /DF' },
  { antiquity: '40', name: 'RAFAEL DE MENEZES TORRES', omp: 'BPESC' },
  { antiquity: '41', name: 'SEVERINO SERGIO SOARES DA FONSECA', omp: 'L.E.' },
  { antiquity: '42', name: 'FERNANDO CARDOSO SOUZA', omp: 'APM' },
  { antiquity: '43', name: 'CLEBERVAN AZEVEDO DE ALBUQUERQUE', omp: 'BPESC/CORREG' },
  { antiquity: '44', name: 'MARCOS ROSA DA SILVA DOS SANTOS', omp: 'PM5' },
  { antiquity: '45', name: 'JONATA APOLINARIO CALHEIROS', omp: '10º BPM' },
  { antiquity: '47', name: 'JONAS ALYSSON REGO DA SILVA', omp: 'ROTAM' },
  { antiquity: '48', name: 'JULIANA SOFIA SILVA VIEIRA', omp: 'BPESC/DCS' },
  { antiquity: '49', name: 'AUDERAN VIRTUOSO BISPO', omp: 'BPTRAN' },
  { antiquity: '50', name: 'RAPHAEL VIEIRA MARINHO', omp: '6º BPM' },
  { antiquity: '51', name: 'ALMIR EDUARDO CORREIA PEREIRA', omp: '7ª CPM/I' },
  { antiquity: '52', name: 'ZAQUEU DE LIMA OLIVEIRA FILHO', omp: 'COPES' },
  { antiquity: '53', name: 'HELVIS CORRÊA DE BARROS', omp: 'BOPE' },
  { antiquity: '54', name: 'ALINY THAYSA FERNANDES TEIXEIRA', omp: 'DPP' },
  { antiquity: '56', name: 'ARTUR VICTOR LINS DA SILVA', omp: '9ª CPM/I' },
  { antiquity: '57', name: 'MOISES GOMES DOS SANTOS JUNIOR', omp: 'GCG' },
  { antiquity: '58', name: 'LUIZ FERNANDO FRANÇA DE ARAÚJO', omp: 'CPFAZ' },
  { antiquity: '59', name: 'JEFFERSON MURILO GONÇALVES SILVA', omp: 'RPMON' },
  { antiquity: '60', name: 'VALDEMAR FRANCISCO PEREIRA FILHO', omp: '9º BPM' },
  { antiquity: '61', name: 'FABRÍCIO LEITE SALES', omp: 'DINT' },
  { antiquity: '63', name: 'EDVALDO HENRIQUE DOS SANTOS BASILIO', omp: 'RPMON' },
  { antiquity: '64', name: 'YAGO FRANCISCO DE FRANÇA CLEMENTE', omp: 'DINT' },
  { antiquity: '65', name: 'MAYR WAGNER BARROS INACIO', omp: '5º BPM' },
  { antiquity: '66', name: 'RENATO BATISTA SANTOS', omp: 'BPRV/9 CPM/I' },
  { antiquity: '67', name: 'SAULLO DANTAS DA ROCHA', omp: 'DLOG' },
  { antiquity: '69', name: 'RUBENS ANDRADE DE MELO JUNIOR', omp: 'BPRV' },
  { antiquity: '70', name: 'RAPHAEL CAVALCANTE ALÉCIO', omp: '3º BPM' },
  { antiquity: '71', name: 'ALYSON BARBOSA DA SILVA GALVÃO', omp: '2º BPM' },
  { antiquity: '72', name: 'KAROL DIAS ALVES', omp: '2ª CPM/I' },
  { antiquity: '73', name: 'JOÃO PAULO TENÓRIO DE OLIVEIRA', omp: '5º BPM' },
  { antiquity: '74', name: 'JOÃO FELIPE DE ALBUQUERQUE ARAÚJO', omp: '6º BPM' },
  { antiquity: '75', name: 'CARLOS ANDRÉ SÁ DA SILVA', omp: '7º BPM' },
  { antiquity: '76', name: 'LEANDRO BARROS DOS SANTOS', omp: 'APM' },
  { antiquity: '77', name: 'MARTINHO DE ARAUJO JOVINO JUNIOR', omp: '9º BPM' },
  { antiquity: '78', name: 'MÁRIO MELO DOS SANTOS JÚNIOR', omp: '11º BPM' },
  { antiquity: '79', name: 'IAGO ANTONIO DOS SANTOS OMENA', omp: 'ROTAM' },
  { antiquity: '80', name: 'WHOTSON BATISTA DOS SANTOS', omp: 'ROTAM' },
  { antiquity: '81', name: 'DIEGO ALMEIDA SANTOS', omp: '3º BPM' },
  { antiquity: '82', name: 'MARCOS HENRIQUE TENÓRIO RIBEIRO', omp: 'CPFAZ' },
  { antiquity: '84', name: 'JAILSON COSTA DE LIMA', omp: '7º BPM' },
  { antiquity: '85', name: 'LENILSON DIAS DE QUEIROZ', omp: '3º BPM' },
  { antiquity: '86', name: 'WILLAMS DA SILVA SANTOS', omp: 'BOPE' },
  { antiquity: '87', name: 'LUCAS HENRIQUE MAGALHÃES PINTO', omp: 'BOPE' },
  { antiquity: '88', name: 'WAGNER EDUARDO GERVASIO GOMES', omp: 'PM3' },
  { antiquity: '89', name: 'PABLO DE TARSO CAVALCANTE', omp: '7º BPM' },
  { antiquity: '90', name: 'ERALDO MOREIRA DA SILVA FILHO', omp: '2º BPM' },
  { antiquity: '91', name: 'JOSE KLEBER SANTOS LIMA', omp: '5º BPM' },
  { antiquity: '92', name: 'CHARLANDISON RODRIGUES DOS SANTOS', omp: '6º BPM' },
  { antiquity: '93', name: 'GERBESON ROMAO DA COSTA', omp: 'ROTAM' },
  { antiquity: '94', name: 'BIANCA ALBUQUERQUE CAVALCANTE', omp: 'GCG' },
  { antiquity: '95', name: 'JOSÉ FERNANDO DE OLIVEIRA CIRILO FILHO', omp: 'BOPE' },
  { antiquity: '96', name: 'JOEL DJALMA DE SOUZA', omp: '4ª CPM/' },
  { antiquity: '97', name: 'VICTOR HUGO DE OLIVEIRA E SILVA', omp: 'L.E.' },
  { antiquity: '98', name: 'ALEXANDRE CORREIA SOARES', omp: 'APM' },
  { antiquity: '99', name: 'PEDRO VINICYOS VIEIRA SANTOS', omp: '9º BPM' },
  { antiquity: '100', name: 'ARQUIMEDES BESERRA DOS SANTOS', omp: '14º BPM' },
  { antiquity: '101', name: 'MIGUEL SEBASTIAO OLIVEIRA JUNIOR', omp: 'BOPE' },
  { antiquity: '102', name: 'WERICK MEDEIROS ALVES', omp: '5ª CPM/I' },
  { antiquity: '103', name: 'GLAUBERTO YGOR GOMES DOS SANTOS ROCHA', omp: '14º BPM' },
  { antiquity: '104', name: 'LEONARDO PEIXOTO PANSERI', omp: 'CFAP' },
  { antiquity: '105', name: 'RAFAEL DOUGLAS DE MESQUITA SILVA', omp: '13º BPM' },
];

export const TEN_QOE_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'NILSON FERREIRA DE OLIVEIRA', omp: 'BPRV' },
  { antiquity: '2', name: 'UBIRATAN LEITE DA SILVA', omp: '5ª CPMI' },
  { antiquity: '4', name: 'JOSIVAL SANTOS FALCAO', omp: 'DINT' },
  { antiquity: '5', name: 'WILMA DA SILVA LIMA CORREIA', omp: 'DPS' },
  { antiquity: '6', name: 'MARCIA DA SILVA MORAES BELARMINO', omp: 'GCG/CORREG' },
  { antiquity: '7', name: 'JOSÉ WELLINGTON DO NASCIMENTO', omp: '4º BPM' },
  { antiquity: '9', name: 'CLAUDEMIR MOISÉS DA SILVA', omp: 'BPRV/DLOG' },
  { antiquity: '8', name: 'ROSIVAN SANTOS DO NASCIMENTO', omp: '2º BPM' },
  { antiquity: '10', name: 'GENIVALDO BESERRA DE LIMA FARIAS', omp: '11º BPM/1ª CPM/I' },
  { antiquity: '11', name: 'LUCIANA VALÉRIA BUARQUE DA SILVA', omp: 'APM' },
  { antiquity: '12', name: 'JAILSON LIMA DOS SANTOS', omp: '9º BPM' },
  { antiquity: '13', name: 'NOÊMIA DOLORES VIEIRA DE OLIVEIRA', omp: 'BPESC' },
  { antiquity: '14', name: 'LUCIVANIO SILVERIO DA MOTA', omp: '3ª CPM/I' },
  { antiquity: '16', name: 'ROBERALDO ALMEIDA DO NASCIMENTO', omp: '7ª CPM/I' },
  { antiquity: '17', name: 'CLERIVALDO LOURENÇO COSTA', omp: 'PM4/DLOG' },
  { antiquity: '18', name: 'LEONARDO JORGE DA SILVA PACHECO', omp: 'CFAP' },
  { antiquity: '19', name: 'JOSE DE LIMA LINS', omp: 'DPP' },
  { antiquity: '20', name: 'DOUGLAS SANTOS MAGALHÃES', omp: 'ADIDO ESPECIAL RESERVA' },
  { antiquity: '21', name: 'CÍCERO SÉRGIO MARINHO REIS BRANCO', omp: '5ª CPMI' },
  { antiquity: '22', name: 'CLAUDIO JORGE COUTINHO FERREIRA', omp: '13º BPM' },
  { antiquity: '23', name: 'EDILSON LOPES DA SILVA', omp: '3º BPM' },
  { antiquity: '24', name: 'ERISVALDO RODRIGUES PEREIRA', omp: '6ª CPM/I' },
  { antiquity: '25', name: 'JACKSON DE AMORIM FERREIRA', omp: 'BOPE' },
  { antiquity: '26', name: 'LAURO LUCIO DE OLIVEIRA', omp: 'DLOG' },
  { antiquity: '27', name: 'WELLINGTON CÂNDIDO DOS SANTOS', omp: 'PRMON' },
  { antiquity: '28', name: 'CARLOS ANTONIO DE ALBUQUERQUE REIS', omp: '8º BPM' },
  { antiquity: '30', name: 'ALEX OLIVEIRA DE ARAUJO', omp: '5º BPM' },
  { antiquity: '31', name: 'LUCIANO VIEIRA DE LIMA', omp: 'GCG' },
  { antiquity: '33', name: 'CHARLES JOSÉ DOS SANTOS', omp: '1ª CPM/I' },
  { antiquity: '34', name: 'EDVALDO SANTOS', omp: '11º BPM' },
  { antiquity: '36', name: 'JOSÉ LIMA DA SILVA', omp: 'AGUARDANDO RESERVA' },
  { antiquity: '37', name: 'BEROALDO ROBSON DE ARAUJO MELO', omp: '4ª CPM/I' },
  { antiquity: '38', name: 'JAILSON GOMES DA SILVA', omp: '6º BPM' },
  { antiquity: '39', name: 'SIVALDO JOSE FERREIRA', omp: 'DS' },
  { antiquity: '40', name: 'ELIAS SANTANA NETO', omp: '7ª CPM/I' },
  { antiquity: '41', name: 'CLODOALDO RAIMUNDO DA SILVA', omp: '1º BPM' },
  { antiquity: '42', name: 'JOSE ELIAS DOS SANTOS FILHO', omp: 'CPMC' },
  { antiquity: '44', name: 'JOSE FABRICIO DE OLIVEIRA', omp: 'L.E.' },
  { antiquity: '45', name: 'JOSÉ ANTONIO SOARES', omp: '10ª CPMI' },
  { antiquity: '46', name: 'JOSÉ CLEITON BENTO DA SILVA', omp: '12º BPM' },
  { antiquity: '47', name: 'HENRIQUE DE ARAÚJO DA SILVA', omp: 'DPP' },
  { antiquity: '48', name: 'LUZIA VILELA DE ARAÚJO', omp: 'DP/DCS' },
  { antiquity: '49', name: 'CLEVIO DA SILVA NETO', omp: 'DS' },
  { antiquity: '50', name: 'ROBERTO RODRIGUES DOS SANTOS', omp: '14º BPM/ DPS' },
  { antiquity: '51', name: 'JOSÉ CLÁUDIO DA SILVA', omp: 'BPTRAN' },
  { antiquity: '52', name: 'JOSÉ CRISTIANO COSTA', omp: 'BPRV' },
  { antiquity: '53', name: 'RAIMUNDO PEREIRA GOMES', omp: '2ª CPM/I' },
  { antiquity: '54', name: 'JOSE ROBERTO ALVES DE LIMA', omp: '7º BPM' },
  { antiquity: '55', name: 'ANTONIO SANTOS DE SANTANA', omp: '11º BPM' },
  { antiquity: '56', name: 'CHARLES ALMEIDA SANTANA', omp: '10º BPM' },
  { antiquity: '57', name: 'JOSÉ UILSON DE MORAES', omp: '3º BPM' },
  { antiquity: '58', name: 'ANTONIO RODRIGUES DE SOUZA FILHO', omp: 'L.E.' },
  { antiquity: '59', name: 'WILLAMS LEITE DE OLIVEIRA', omp: '3ª CPM/I' },
  { antiquity: '60', name: 'MARCOS ANTÔNIO ALVES DOS SANTOS', omp: 'AJD GERAL' },
  { antiquity: '61', name: 'JOSÉ BELARMINO DA SILVA FILHO', omp: 'DEFD' },
  { antiquity: '64', name: 'JOSE LAERCIO CORREA JUNIOR', omp: '13º BPM' },
  { antiquity: '65', name: 'FLÁVIO GOMES', omp: 'BPA' },
  { antiquity: '66', name: 'SEVERINO DOS SANTOS VIEIRA', omp: 'CPMC' },
];

export const TEN2_QOE_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'VANILDO GUEDES ALEXANDRE', omp: '8º BPM' },
  { antiquity: '2', name: 'JOSÉ FERNANDES DA COSTA NETO', omp: '13º BPM' },
  { antiquity: '3', name: 'GEDSON DA SILVA ATAÍDE', omp: '2ª CPM/I' },
  { antiquity: '6', name: 'ROMULO NOGUEIRA DE LIMA', omp: '5ª CPM/I' },
  { antiquity: '7', name: 'JOSE CARLOS CAVALCANTI', omp: '5ª CPM/I' },
  { antiquity: '8', name: 'CLEDISVALDO DOS SANTOS SILVA', omp: '10ª CPM/I' },
  { antiquity: '9', name: 'JOSEILTON MINERVINO DE ATAIDE', omp: 'DS' },
  { antiquity: '11', name: 'ASCANIO JOÃO DA SILVA', omp: '6º BPM' },
  { antiquity: '12', name: 'JOSELITO SANTOS DE SANTANA', omp: 'DLOG' },
  { antiquity: '13', name: 'ABRAÃO DE OLIVEIRA LEOPOLDINO', omp: 'DPP' },
  { antiquity: '14', name: 'ADRIANO ALEXANDRE COSTA BITTENCOURT', omp: '1ª CPM/I' },
  { antiquity: '15', name: 'CICERO VITURINO DA ROCHA', omp: '8º BPM' },
  { antiquity: '16', name: 'MARIA LUCIA SILVERIO CAVALCANTE', omp: 'BPRV' },
  { antiquity: '17', name: 'ROBSON VITORIANO DA SILVA', omp: '2ª CPM/I' },
  { antiquity: '18', name: 'JOSUE MARTINS DA SILVA', omp: '2ª CPM/I' },
  { antiquity: '19', name: 'JOSÉ BENEVALDO DA ROCHA SILVA', omp: 'PM3' },
  { antiquity: '20', name: 'FÁBIO PASTOR DOS SANTOS', omp: 'CORREG' },
  { antiquity: '21', name: 'HELDER FERNANDO CONCEIÇÃO', omp: 'DPS' },
  { antiquity: '22', name: 'PAULO SERGIO ALVES', omp: 'CPCHOQUE' },
  { antiquity: '23', name: 'KLETIANE DOS SANTOS SILVA', omp: 'CORREG' },
  { antiquity: '24', name: 'JOÃO RICARDO GOMES BARBOSA', omp: '5ª CPM/I' },
  { antiquity: '25', name: 'GISLAIDE ALCANTARA DA SILVA LARANJEIRA', omp: 'CPMC' },
  { antiquity: '26', name: 'LILIANE SILVA RODRIGUES', omp: 'CORREG' },
  { antiquity: '27', name: 'ALEXANDRE HENRIQUE TEXIERA BEZERRA', omp: '9º BPM' },
  { antiquity: '28', name: 'ALDO IRIS DOS SANTOS', omp: 'CPMC' },
  { antiquity: '29', name: 'JAILSON JOSÉ DOS SANTOS', omp: 'CPMC' },
  { antiquity: '30', name: 'AILTON ROTHARDAN SILVA SANTOS', omp: 'DF' },
  { antiquity: '31', name: 'CARLOS EDUARDO JUELLE', omp: 'DINT' },
  { antiquity: '32', name: 'JOAO FRANCISCO DOS SANTOS', omp: 'L.E.' },
  { antiquity: '33', name: 'JOSÉ ALBERTO ALVES VIEIRA', omp: '8ª CPM/I' },
  { antiquity: '34', name: 'SANDRO EDUARDO DE MELO', omp: 'BPA' },
  { antiquity: '36', name: 'RONALDO SILVA DOS SANTOS', omp: '12º BPM' },
  { antiquity: '37', name: 'LILIANE SANTOS REIS', omp: 'DP' },
  { antiquity: '39', name: 'ADISTENEY DA SILVA SANTOS', omp: 'DS' },
  { antiquity: '40', name: 'OSCAR VIEIRA DE MELO JUNIOR', omp: 'DF' },
  { antiquity: '41', name: 'JESIMIEL SANTOS DA SILVA', omp: 'PM1/DPS' },
  { antiquity: '42', name: 'VALTER JACINTO DA SILVA', omp: 'GCG' },
  { antiquity: '44', name: 'GUTEMBERG MATIAS DE LIMA', omp: 'DEIP' },
  { antiquity: '46', name: 'EDVALDO DA SILVA', omp: '10ª CPM/I' },
  { antiquity: '47', name: 'NIVALDO MACEDO DOS SANTOS', omp: '12º BPM' },
  { antiquity: '48', name: 'SAMUEL DE TACIO DA SILVA', omp: '1º BPM' },
  { antiquity: '49', name: 'JEBSON MARCIO MELO BARBOSA', omp: '7ª CPM/I' },
  { antiquity: '50', name: 'JOSÉ MÁRCIO FIGUEIRA ALVES', omp: 'DP' },
  { antiquity: '51', name: 'MARCOS VINICIUS CARVALHO', omp: '4ª CPM/I' },
  { antiquity: '52', name: 'SAMUEL VITORINO GOMES', omp: '4º BPM' },
  { antiquity: '53', name: 'ROBSON LIMA DOS SANTOS', omp: 'RPMON' },
  { antiquity: '54', name: 'MARIO JORGE DO NASCIMENTO SANTOS', omp: '12º BPM' },
  { antiquity: '55', name: 'ELEILDO GOMES DOS SANTOS', omp: '3ª CPM/I' },
  { antiquity: '56', name: 'VANILSON CESAR DA SILVA', omp: 'APM' },
  { antiquity: '58', name: 'ADENILTON ROMULO GONÇALVES DA SILVA', omp: 'DPP' },
  { antiquity: '59', name: 'DIOCLECIO DUARTE RAMOS NETO', omp: 'RPMON' },
  { antiquity: '60', name: 'CARLES ADRIANO ALVES CARDOSO', omp: '2º BPM' },
  { antiquity: '61', name: 'ANTONIO DOS SANTOS BARBOSA', omp: 'RPMON' },
  { antiquity: '62', name: 'LUCIFLAVIA FRANÇA DE VASCONCELOS BARROS', omp: 'DINT' },
  { antiquity: '63', name: 'ANDRE DIAS DA COSTA', omp: 'CPCHOQUE' },
  { antiquity: '64', name: 'LOURIVAL COSTA ROMEIRO', omp: 'DINT' },
  { antiquity: '65', name: 'MARCOS LUIZ MARTINIANO DA SILVA', omp: '2º BPM' },
  { antiquity: '66', name: 'MARCOS SOARES PAUFERRO', omp: '7º BPM' },
  { antiquity: '67', name: 'JAILSON CORREIA MOTA', omp: '7ª CPM/I' },
  { antiquity: '68', name: 'TANENWALBER DA SILVA MENEZES', omp: 'BOPE/5ª CPM/I' },
  { antiquity: '69', name: 'FLÁVIA CRISTINA MIGUEL DOS SANTOS', omp: 'BPESC' },
  { antiquity: '70', name: 'JOSE WELLINGTON DOS SANTOS', omp: 'CFAP' },
  { antiquity: '71', name: 'ALEXANDRE FERREIRA FREIRE', omp: 'L.E.' },
  { antiquity: '72', name: 'ADEJALBAS ASSIS DO NASCIMENTO', omp: '1º BPM' },
  { antiquity: '73', name: 'CLAUDEVAN DA SILVA CLAUDINO', omp: 'CPMC' },
  { antiquity: '74', name: 'GIVALDO FERREIRA DA SILVA FILHO', omp: 'RAIO' },
  { antiquity: '76', name: 'REJANE NASCIMENTO DE ASSUNÇÃO BATISTA', omp: 'CORREG' },
  { antiquity: '77', name: 'MARCELO SANTOS DO NASCIMENTO', omp: '8ª CPM/I' },
  { antiquity: '78', name: 'JONES XAVIER DA JUSTA', omp: '14º BPM' },
  { antiquity: '79', name: 'NILSON FERREIRA LUCIANO', omp: '14º BPM' },
  { antiquity: '80', name: 'JOSE ROBERTO GOMES DE OLIVIERA', omp: 'APM' },
  { antiquity: '81', name: 'JOSÉ FÁBIO DO NASCIMENTO', omp: 'CFAP' },
  { antiquity: '82', name: 'NEILTON DOS SANTOS', omp: '8ª CPM/I' },
  { antiquity: '83', name: 'JOSIVAN PEREIRA DA SILVA', omp: 'DPP' },
  { antiquity: '84', name: 'EDNA APARECIDA VIEIRA SANTOS', omp: 'BPESC' },
  { antiquity: '85', name: 'CLEZIVALDO COSTA SALES', omp: 'BPTRAN' },
  { antiquity: '86', name: 'JOÃO ROBERTO DE LIRA SANTOS', omp: 'GCG' },
  { antiquity: '87', name: 'SADY DE LIMA', omp: '4º BPM' },
  { antiquity: '88', name: 'RENATO TAVARES DE FREITAS', omp: '13º BPM' },
  { antiquity: '89', name: 'MÁRCIO SANTOS REIS', omp: 'CPFAZ/ 13º BPM' },
  { antiquity: '90', name: 'URIEL DOS SANTOS PEREIRA', omp: '1ª CPM/I' },
  { antiquity: '91', name: 'JOSE RICARDO DA SILVA LINS', omp: 'CORREG' },
  { antiquity: '92', name: 'JOSE CICERO MARQUES DOS SANTOS', omp: '6º BPM' },
  { antiquity: '93', name: 'SIVONALDO JOSE MEDEIROS', omp: 'DS' },
  { antiquity: '94', name: 'DAILSON DOS SANTOS BARROS', omp: 'CME' },
  { antiquity: '95', name: 'EDSON PEREIRA DA ROCHA', omp: 'PM5/AJD' },
  { antiquity: '96', name: 'MANOEL FEIJO FRANCA', omp: '14º BPM/CPRNZM' },
  { antiquity: '97', name: 'RONALDO ALBUQUERQUE DE OLIVEIRA', omp: 'DEFD' },
  { antiquity: '98', name: 'PEDRO RICARDO MENDES DE VASCONCELOS', omp: '6º BPM' },
  { antiquity: '100', name: 'FERNANDO JOSE DA SILVA', omp: '14º BPM' },
  { antiquity: '101', name: 'CARLOS JOSÉ GOMES DOS SANTOS', omp: 'RAIO' },
  { antiquity: '103', name: 'MAURO TEIXEIRA DE MENDONÇA', omp: 'DPP' },
  { antiquity: '104', name: 'VANDERLEI RODRIGUES LIMA', omp: 'CPMC' },
  { antiquity: '105', name: 'ANA LUCIA FERNANDES DE SOUZA', omp: 'DPS' },
  { antiquity: '106', name: 'AÍLSON JOSÉ LIMA DA SILVA', omp: 'DPS' },
  { antiquity: '108', name: 'PEDRO VIEIRA DA GAMA', omp: '3ª CPMI' },
  { antiquity: '109', name: 'CICERO JOSE DOS SANTOS SOUZA', omp: '7º BPM' },
  { antiquity: '110', name: 'JOSÉ CLÁUDIO AMARAL DA SILVA', omp: 'BPTRAN' },
  { antiquity: '111', name: 'ROBERTO JOSE HONORATO DOS SANTOS', omp: 'DLOG' },
  { antiquity: '113', name: 'PEDRO BERTULINO DA SILVA FILHO', omp: '2º BPM' },
  { antiquity: '114', name: 'RODRIGO LINS DA ROCHA', omp: 'BPESC' },
  { antiquity: '115', name: 'ACACIO CORREIA MACHADO', omp: 'CPRS' },
  { antiquity: '116', name: 'JOSÉ MARCOS DOS SANTOS', omp: '5ª CPM/I' },
  { antiquity: '117', name: 'HELIOMAR MEDEIROS DE MORAIS', omp: '13º BPM' },
  { antiquity: '118', name: 'MILTON JOSÉ DOS SANTOS', omp: 'CFAP' },
  { antiquity: '119', name: 'MARCELO SOARES PAUFERRO', omp: '7º BPM' },
  { antiquity: '120', name: 'EDNALDO LOPES DOS SANTOS', omp: '5ª CPM/I' },
  { antiquity: '121', name: 'ELITON ROBERTO SERAFIM DA SILVA', omp: '5º BPM' },
  { antiquity: '122', name: 'CLÉBIO RICARDO DE OLIVEIRA', omp: 'GCG' },
  { antiquity: '123', name: 'JOSÉ ALMIR NEVES DA SILVA', omp: 'BPA' },
  { antiquity: '124', name: 'LUIZ CARLOS BATISTA DA SILVA', omp: 'DPS' },
  { antiquity: '125', name: 'CLAUDEVAN SANTOS DOS ANJOS', omp: 'DLOG' },
  { antiquity: '126', name: 'EDSON JOSE ALCIDES GOMES', omp: '3ª CPM/I' },
  { antiquity: '127', name: 'JOSE LEONCIO DOS SANTOS JUNIOR', omp: '1º BPM' },
  { antiquity: '128', name: 'JOSE LENILDO DOS SANTOS', omp: 'BOPE' },
  { antiquity: '129', name: 'DAVI DE MOURA SILVA', omp: 'ADIDO DP' },
];

export const ASP_ANTIQUITY: AntiquityRecord[] = [
  { antiquity: '1', name: 'ERICSON SIMIÃO ALVES', omp: 'BPRV' },
  { antiquity: '2', name: 'MADSON FILIPE SANTOS VIANA HENRIQUE', omp: 'BPTRAN' },
  { antiquity: '3', name: 'LAMARTINE DE ARAÚJO MARA JUNIOR', omp: '6º BPM' },
  { antiquity: '4', name: 'DAVID PITER FERREIRA DE OLIVEIRA', omp: '3º BPM' },
  { antiquity: '5', name: 'ERIVALDO MARINHO PITA NETO', omp: 'BOPE' },
  { antiquity: '6', name: 'RODRIGO CHAVES DOS SANTOS', omp: '4º BPM' },
  { antiquity: '7', name: 'PAULO RODRIGO TENÓRIO CALAÇA', omp: 'RPMON' },
  { antiquity: '8', name: 'PEDRO VITOR ALBUQUERQUE RIBEIRO ACIOLI', omp: '1º BPM' },
  { antiquity: '9', name: 'NAYARA CONDJA FERREIRA DO NASCIMENTO', omp: 'ROTAM' },
  { antiquity: '10', name: 'LUÍS FELIPE DA SILVA', omp: '3ª CPMI' },
  { antiquity: '11', name: 'LEONARDO AMADEU ARAUJO DE OLIVEIRA', omp: 'BPA' },
  { antiquity: '12', name: 'DIEGO RODRIGO LAGEDO SANTANA', omp: '14º BPM' },
  { antiquity: '13', name: 'PEDRO ANTÔNIO BULHÕES DE OLIVEIRA HOLANDA', omp: '7º BPM' },
  { antiquity: '14', name: 'SORAIA FERREIRA DA SILVA', omp: 'BPESC' },
  { antiquity: '15', name: 'LUIZ GUSTAVO DE ALBUQUERQUE ARAUJO RODRIGUES', omp: '4ª CPMI' },
  { antiquity: '16', name: 'ALEXANDRE ROSA DA SILVA DOS SANTOS', omp: 'RAIO' },
  { antiquity: '17', name: 'JOSÉ ALDAIR FERREIRA FELIX', omp: '8º BPM' },
  { antiquity: '18', name: 'TAINNES COSTA ARAUJO', omp: '9ª CPMI' },
  { antiquity: '19', name: 'ROMILSON LESSA ARAUJO FILHO', omp: '12º BPM' },
  { antiquity: '20', name: 'DANIELLY CRISTHINY SANTOS BRITO', omp: '1ª CPMI' },
  { antiquity: '21', name: 'CRISTHIAN LUCAS SANTOS OLIVEIRA', omp: '1º BPM' },
  { antiquity: '22', name: 'CARLA DE AZEVEDO VITAL', omp: '2º BPM' },
  { antiquity: '23', name: 'ROGÉRIO WILLIAN SOUTO TAVARES', omp: 'BOPE' },
  { antiquity: '24', name: 'ADRIANO DA SILVA ROCHA', omp: '5º BPM' },
  { antiquity: '25', name: 'RICKY ANDREY SANTOS ANDRADE', omp: '5ª CPMI' },
  { antiquity: '26', name: 'ALCIDES TENORIO DA SILVEIRA', omp: '10º BPM' },
  { antiquity: '27', name: 'DANIEL LIMA BITENCOURT DE SOUZA', omp: 'CPCHOQUE' },
  { antiquity: '28', name: 'IRAN ALVES DA SILVA JUNIOR', omp: '12º BPM' },
  { antiquity: '29', name: 'JOÃO VITOR CALIXTO ROCHA', omp: '6ª CPMI' },
  { antiquity: '30', name: 'LEONNY DE OLIVEIRA SANTOS', omp: '10º BPM' },
  { antiquity: '31', name: 'LUCAS RAFAEL NUNES SANTOS', omp: '5º BPM' },
  { antiquity: '32', name: 'JOSE MATEUS NUNES DOS SANTOS', omp: 'RAIO' },
  { antiquity: '33', name: 'DANIEL SILVA DA CRUZ SANTANA', omp: '2º BPM' },
  { antiquity: '34', name: 'MARCONDE PHILIPE SANTOS SILVA', omp: 'COPES' },
  { antiquity: '35', name: 'VINÍCIUS JÚLIO SILVA DE FARIAS', omp: '7ª CPMI' },
  { antiquity: '36', name: 'CATARINE RÉGEA CAVALCANTE PEIXOTO SILVA', omp: '2ª CPMI' },
  { antiquity: '37', name: 'DANIEL MACHADO DA SILVA NETO', omp: '14º BPM' },
  { antiquity: '38', name: 'RELVIS ANTOFRAN HONORATO DA SILVA', omp: 'CPFAZI' },
  { antiquity: '39', name: 'KAIO COURA MELO PACHECO', omp: 'ROTAM' },
  { antiquity: '40', name: 'GUSTAVO MACEDO ANDRADE MONTEIRO', omp: 'COPES' },
  { antiquity: '41', name: 'JOSE FERREIRA DOS SANTOS JUNIOR', omp: '11º BPM' },
  { antiquity: '42', name: 'THIAGO AUGUSTO OLIVEIRA BISPO', omp: '7º BPM' },
  { antiquity: '43', name: 'DANILLO CAVALCANTE NAZÁRIO', omp: '3º BPM' },
  { antiquity: '44', name: 'FRANCISCO LUCAS CAMPOS PRADO', omp: '11º BPM' },
  { antiquity: '45', name: 'ANTONIO FERNANDO DE CARVALHO NETO', omp: '9º BPM' },
  { antiquity: '46', name: 'LUIZ FELIPE VIRGENS FRAGA', omp: 'CPCHOQUE' },
  { antiquity: '47', name: 'KELVY MACEDO DOS SANTOS', omp: '6º BPM' },
  { antiquity: '48', name: 'ADRIENE DE JESUS MARCHIORI', omp: '13º BPM' },
  { antiquity: '49', name: 'PEDRO VINÍCIUS GUEDES BRAGA', omp: '9º BPM' },
  { antiquity: '50', name: 'JOÃO ARTHUR PEREIRA DA PAZ', omp: 'CPCHOQUE' },
  { antiquity: '51', name: 'WELDES MOTA SANTOS', omp: 'RPMON' },
  { antiquity: '52', name: 'JOSÉ RODRIGO SERRA MIZIARA', omp: '8ª CPMI' },
];
