
import { RankPost, OfficerData } from './types';

export const INITIAL_DATA: OfficerData[] = [
  { id: '1', rank: RankPost.CEL, fixed: 20, occupied: 20, surplus: 0, surplusOfficers: [] },
  { 
    id: '2', 
    rank: RankPost.TC, 
    fixed: 60, 
    occupied: 68, 
    surplus: 8, 
    surplusOfficers: [
      { name: 'JOSE DANIEL DE LIMA NETO', role: 'Corregedor', sector: 'CG', antiquity: '2' },
      { name: 'ANAXIMANDRO TENORIO DE SA', role: 'Comandante do CPRA', sector: 'CPRA', antiquity: '6' },
      { name: 'PHELIPE ROGERIO DOS SANTOS', role: 'Diretor de Pessoal', sector: 'DP', antiquity: '28' },
      { name: 'HENRIQUE JATOBA CORREIA', role: 'Comandante do CME', sector: 'CME', antiquity: '48' },
      { name: 'SILVIO JOSE LUCIO E SILVA', role: 'Diretor de Comunicação Social', sector: 'DCS', antiquity: '45' },
      { name: 'HIRAQUE AGNNES DOS SANTOS', role: 'Comandante do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '46' },
      { name: 'THIAGO DE MORAES DUARTE OLIVEIRA', role: 'Diretor de Inteligência', sector: 'DINT', antiquity: '73' },
      { name: 'FERNANDO JOSE FERREIRA SOARES JUNIOR', role: 'Comandante do CPRSUL', sector: 'CPRSUL', antiquity: '74' }
    ] 
  },
  { 
    id: '3', 
    rank: RankPost.MAJ, 
    fixed: 140, 
    occupied: 169, 
    surplus: 29, 
    surplusOfficers: [
      { name: 'ROBERTO SANTOS PEREIRA', role: 'Chefe do Centro de Motomecanização da Diretoria de Logística', sector: 'DLOG', antiquity: '1' },
      { name: 'ADRIANO LEVY MONTEIRO SANTOS', role: 'Comandante do 14º BPM', sector: '14º BPM', antiquity: '10' },
      { name: 'ANTONIO UMBELINO DOS SANTOS FILHO', role: 'Chefe da Seção de Planejamento Educacional e Formação Continuada (DE/2)', sector: 'DEIP', antiquity: '14' },
      { name: 'RODRIGO VITAL VELOSO SOARES BOTELHO', role: 'Comandante do 8º BPM', sector: '8º BPM', antiquity: '21' },
      { name: 'ADEILSON LINS DE CARVALHO', role: 'SPO', sector: 'SPO', antiquity: '22' },
      { name: 'DANIEL SAMPAIO VALOES DA ROCHA', role: 'Comandante do Centro de Formação e Aperfeiçoamento de Praças', sector: 'CFAP', antiquity: '23' },
      { name: 'CICERO JOSE NAVARRO FERRO', role: 'Chefe da Seção de Controle de Gestão e Assentamento (DP/1)', sector: 'DP', antiquity: '29' },
      { name: 'DANIEL SOUZA DOS SANTOS', role: 'Comandante do 13º BPM', sector: '13º BPM', antiquity: '39' },
      { name: 'JOSUÉ DOS SANTOS SOUZA ELIZIÁRIO', role: 'Subdiretor de Inteligência', sector: 'DINT', antiquity: '42' },
      { name: 'JOSE AGNO DA SILVA', role: 'Chefe da Seção de Orçamento da Diretoria de Finanças', sector: 'DF', antiquity: '43' },
      { name: 'CLAUDIO VICTOR DE OLIVEIRA AMORIM', role: 'Chefe do Grupamento Aéreo', sector: 'GCG', antiquity: '46' },
      { name: 'GLAUDSON JATOBA DE OLIVEIRA', role: 'Comandante do 4º BPM', sector: '4º BPM', antiquity: '47' },
      { name: 'ARLAN SIQUEIRA DE BARROS', role: 'Chefe da SPP', sector: 'SSP', antiquity: '49' },
      { name: 'NOEMI GOMES FIRMO SOARES', role: 'Comandante do BPESC', sector: 'CPE', antiquity: '52' },
      { name: 'DAVID DELEON LOPES DA SILVA', role: 'Chefe da Seção de Apoio a Auditória da Justiça Militar', sector: 'CORREG', antiquity: '57' },
      { name: 'EDSON CARLOS BARROS CABRAL DE MELO', role: 'Chefe da Seção de Procedimentos Especiais e Correição', sector: 'CORREG', antiquity: '54' },
      { name: 'DANIEL ALMEIDA SANTOS', role: 'Chefe de Segurança de Voo do Grupamento Aéreo', sector: 'GCG', antiquity: '58' },
      { name: 'BRUNO CERQUEIRA GOMES BARROS', role: 'Chefe da Seção de Pensionistas e Dependentes', sector: 'DPS', antiquity: '59' },
      { name: 'ALEANDRO FERREIRA CAITANO', role: 'Comandante do 6º BPM', sector: '6º BPM', antiquity: '65' },
      { name: 'ANTONIO ANDRE ANDRADE DE OLIVEIRA BARBOSA', role: 'Comandante do 10º BPM', sector: '10º BPM', antiquity: '75' },
      { name: 'JÓVERSON ROCHA DOS SANTOS', role: 'Chefe da Seção de Polícia Judiciária Militar', sector: 'CORREG', antiquity: '77' },
      { name: 'DIEGO HENRIQUE BEZERRA VIEIRA', role: 'Comandante do RPMON', sector: 'RPMON', antiquity: '80' },
      { name: 'VICTOR DUARTE PINHEIRO NETO', role: 'Chefe da Coordenação de Operações', sector: 'DINT', antiquity: '81' },
      { name: 'ÍRIS DAYANA QUEIROZ DE ARAÚJO', role: 'Chefe da Patrulha Maria da Penha e Grupos Vulnerável', sector: 'PMP', antiquity: '84' },
      { name: 'THIAGO ALMEIDA FERREIRA DA SILVA', role: 'Chefe da Coordenação de Análise', sector: 'DINT', antiquity: '86' },
      { name: 'GLAUBER PATRICK DE SANTANA SANTOS', role: 'Comandante do 2º BPM', sector: '2º BPM', antiquity: '89' },
      { name: 'ALUCHAM ARAUJO FONSECA DE SENA', role: 'Subcomandante do CPRM', sector: 'CPRM', antiquity: '91' },
      { name: 'JERCIO TEIXEIRA DE FARIAS', role: 'Comandante do 11º BPM', sector: '11º BPM', antiquity: '97' },
      { name: 'HEQUIAS ALISSON SANTOS PEREIRA', role: 'Comandante do BPM-ROTAM', sector: 'CME', antiquity: '106' }
    ] 
  },
  {
    id: 'qoe-1',
    rank: RankPost.MAJ_QOE,
    fixed: 1,
    occupied: 2,
    surplus: 1,
    surplusOfficers: [
      { name: 'ALBERTO MAGNO SILVA DOS SANTOS', role: 'Chefe da Seção de Folha de Pagamentos', sector: 'DPS', antiquity: '4' }
    ]
  },
  {
    id: 'qoe-cap-maj',
    rank: RankPost.CAP_MAJ_QOE,
    fixed: 0,
    occupied: 3,
    surplus: 3,
    surplusOfficers: [
      { name: 'BENEDITO RODRIGUES FILHO', role: 'Chefe da Seção de Identificação e Registro de Produtos Controlados', sector: 'DINT', antiquity: '13' },
      { name: 'MANOEL GILVANDO DOS SANTOS SILVA', role: 'Subchefe da Assessoria do Comandante Geral', sector: 'CMD', antiquity: '15' },
      { name: 'FLAXIMAN ARRUDA DOS SANTOS', role: 'Subchefe da Seção de Inativos', sector: 'DPS', antiquity: '5' }
    ]
  },
  { 
    id: '4', 
    rank: RankPost.CAP, 
    fixed: 220, 
    occupied: 272, 
    surplus: 52, 
    surplusOfficers: [
      { name: 'ANTONIO HENRIQUE DIAS COSTA', role: 'Comandante da 10ª CPM/I', sector: '10ª CPM/I', antiquity: '2' },
      { name: 'TATIANE CAVALCANTE BARROS', role: 'P3 do Comando de Policiamento da Região Norte e Zona da Mata', sector: 'CPRNZM', antiquity: '6' },
      { name: 'EMANUELLE VITORINO DA SILVA', role: 'Subchefe do COPOM CPRM', sector: 'COPOM/CPRM', antiquity: '11' },
      { name: 'VICENTE NASCIMENTO NETO', role: 'Subcomandante do 2º BPM', sector: '2º BPM', antiquity: '19' },
      { name: 'WENDERSON VIANA GUILHERME', role: 'Subcomandante do 4º BPM', sector: '4º BPM', antiquity: '21' },
      { name: 'EMANOEL PEDRO SANTOS SILVA', role: 'Subcomandante do 3º BPM', sector: '3º BPM', antiquity: '22' },
      { name: 'REVEISON CARVALHO DOS ANJOS', role: 'P2 do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '24' },
      { name: 'DIOGO BUARQUE PEREIRA', role: 'Subcomandante do RPMon', sector: 'RPMON', antiquity: '25' },
      { name: 'MARCUS VINICIUS SILVA CAVALCANTE', role: 'Subcomandante do 9º BPM', sector: '9º BPM', antiquity: '27' },
      { name: 'GRAYSON SAMUEL DA SILVA', role: 'Subcomandante do 1º BPM', sector: '1º BPM', antiquity: '29' },
      { name: 'EVERTON ESTEVAN CABRAL DA SILVA', role: 'Subcomandante do 13º BPM', sector: '13º BPM', antiquity: '33' },
      { name: 'FRANKLIN MELO DOS SANTOS', role: 'Subcomandante do 6º BPM', sector: '6º BPM', antiquity: '34' },
      { name: 'LEONARDO CESAR JORDAO ALVES', role: 'Chefe da Seção de Licitação da Diretoria de Logística', sector: 'DLOG', antiquity: '35' },
      { name: 'JOSE PEDRO DOS ANJOS SILVA', role: 'Comandante da 2ª CPM/I', sector: '2ª CPM/I', antiquity: '38' },
      { name: 'WILLIAMES AZARIAS FLORENCIO DA SILVA', role: 'Chefe da Seção de Inteligência da Diretoria de Inteligência', sector: 'DINT', antiquity: '42' },
      { name: 'THIAGO HENRIQUE BARROS LESSA', role: 'Subchefe da Seção de Pensionistas e Dependentes (DPS)', sector: 'DPS', antiquity: '44' },
      { name: 'LAURICIO GUSTAVO SANTOS DA SILVA', role: 'P1 c/c P4 do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '45' },
      { name: 'CAMILA MARIA GAMA SÁ', role: 'Chefe da Seção de Planejamento e Doutrina de Inteligência', sector: 'DINT', antiquity: '47' },
      { name: 'SAMUEL DE JESUS TELES', role: 'Subcomandante do 10º BPM', sector: '10º BPM', antiquity: '48' },
      { name: 'BRUNO CAVALCANTE PEREIRA', role: 'Chefe da Seção de Relações Institucionais (DCS)', sector: 'DCS', antiquity: '49' },
      { name: 'RODOLPHO HAMUL DE MELO MARINHO', role: 'Comandante da 3ª CPM/I', sector: '3ª CPM/I', antiquity: '52' },
      { name: 'DARLLYNSON NASCIMENTO DOS SANTOS', role: 'Chefe da Subseção de Planejamento de Operações (EMG)', sector: '3ª Seção', antiquity: '53' },
      { name: 'FRANCISCO LUTIANE DE BRITTO', role: 'Comandante da 5ª CPM/I', sector: '5ª CPM/I', antiquity: '54' },
      { name: 'LARISSE LESSA DE BRITO BARBOSA', role: 'Chefe da Assessoria de Relações Institucionais', sector: 'GCG', antiquity: '58' },
      { name: 'MICHEL LINS PIMENTEL', role: 'Subcomandante do BPTran', sector: 'BPTRAN', antiquity: '66' },
      { name: 'WASHINGTON LUIZ MAGALHAES DE MELO FILHO', role: 'Chefe da Seção de Operações (DINT)', sector: 'DINT', antiquity: '67' },
      { name: 'DANIEL PITA AMARAL', role: 'Comandante da RAIO', sector: 'RAIO', antiquity: '68' },
      { name: 'VICTOR LUIZ LOPES DA SILVA', role: 'Chefe da Seção de Inteligência (DINT)', sector: 'DINT', antiquity: '69' },
      { name: 'HUGO GABRIELL DE ALMEIDA', role: 'Chefe da Divisão de Meios da APM', sector: 'APM', antiquity: '70' },
      { name: 'DYBS SANTIAGO DE MELO BARBOSA', role: 'Chefe da Subseção de Captação de Projetos e Convênios', sector: 'PM4', antiquity: '76' },
      { name: 'MARIANA CESAR GOIS CAETANO TOLEDO', role: 'Subchefe da Ajudância Geral', sector: 'AJD GERAL', antiquity: '80' },
      { name: 'CRISLANE MARIA APARECIDA DOS SANTOS CANUTO', role: 'Chefe da Subseção de Controle de mandados (Corregedoria)', sector: 'CORREG', antiquity: '81' },
      { name: 'ISMAEL DA GUIA SILVA', role: 'P3 do Comando de Policiamento Metropolitano', sector: 'CPRM', antiquity: '83' },
      { name: 'LUIZ FELIPE DE OLIVEIRA ROCHA UGA CAMARA', role: 'Comandante da 1ª CPM/I', sector: '1ª CPM/I', antiquity: '86' },
      { name: 'KELMANY MARCIO DE ASSIS SILVA', role: 'Subcomandante do 12º BPM', sector: '12º BPM', antiquity: '91' },
      { name: 'MARIO DE FREITAS GONÇALVES CARNEIRO FILHO', role: 'Subcomandante do 14º BPM', sector: '14º BPM', antiquity: '92' },
      { name: 'SEBASTIAO GRANGEIRO BISNETO', role: 'Subcomandante do BPM-ROTAM', sector: 'ROTAM', antiquity: '93' },
      { name: 'ANDRE LUIS SOUZA DE FIGUEIROA', role: 'Subchefe de Gabinete do Comandante Geral', sector: 'GCG', antiquity: '94' },
      { name: 'EDUARDO HENRIQUE SALUSTIANO SANTOS', role: 'Comandante da 6ª CPM/I', sector: '6ª CPM/I', antiquity: '95' },
      { name: 'LUIZ GUSTAVO DA SILVA BEZERRA', role: 'Chefe da Secretaria do Grupamento Aéreo', sector: 'GCG', antiquity: '98' },
      { name: 'IGOR SARMENTO FIRMINO', role: 'Subchefe da Assessoria do Subcomandante Geral', sector: 'GSCG', antiquity: '99' },
      { name: 'RAQUEL MORAIS DA SILVA VIEGAS', role: 'Chefe do Corpo de Alunos da Academia (APM)', sector: 'APM', antiquity: '100' },
      { name: 'FILLIPE ALMEIDA DE ARAUJO', role: 'Comandante da Companhia de Policiamento de Choque', sector: 'CHOQUE', antiquity: '103' },
      { name: 'JACKELINE LEANDRO DA SILVA', role: 'Chefe da Subseção de procedimentos judiciais (Corregedoria)', sector: 'CORREG', antiquity: '105' },
      { name: 'JEFFERSON CARUZO FERREIRA', role: 'Subcomandante do 8º BPM', sector: '8º BPM', antiquity: '106' },
      { name: 'OSCAR DE FREITAS BEZERRA JUNIOR', role: 'P2 do Comando de Policiamento da Região Norte', sector: 'CPRNZM', antiquity: '107' },
      { name: 'BRUNA RAFAELLE DE ASSIS SANTOS', role: 'Chefe da Subseção de Legislação (EMG)', sector: 'PM1/GCG', antiquity: '109' },
      { name: 'JOSE RENIVALDO DOS SANTOS JÚNIOR', role: 'P2 do Comando de Policiamento da Região Sul', sector: 'CPRSUL', antiquity: '118' },
      { name: 'LYGIA MARIA DA SILVA MÁXIMO', role: 'P3 do Comando de Policiamento Especializado', sector: 'CPE', antiquity: '120' },
      { name: 'PAULO CEZAR SOARES DA SILVA JUNIOR', role: 'Subcomandante do 7º BPM', sector: '7º BPM', antiquity: '121' },
      { name: 'WELLINGTON DOS ANJOS SILVA JUNIOR', role: 'Subcomandante do 5º BPM', sector: '5º BPM', antiquity: '136' },
      { name: 'FABIO CALHEIROS PEREIRA', role: 'Chefe da Seção de Planejamento (GCG)', sector: 'GCG', antiquity: '141' }
    ] 
  },
  { id: '5', rank: RankPost.TEN1, fixed: 300, occupied: 300, surplus: 0, surplusOfficers: [] },
  { id: '6', rank: RankPost.TEN2, fixed: 150, occupied: 150, surplus: 0, surplusOfficers: [] },
];
